import {useEffect,useState} from "react";
import {getContent,latestContent} from "../content/registry";
import {deriveProgress} from "../domain/engine";
import {computeRewards} from "../domain/rewards";
import {csvText,learningEvidence,objectiveCounts,rubricDimensions,rubricStates,type EvidenceAttempt,type RosterMember,type TeacherObservation} from "../domain/assessment";
import type {LearningEvent} from "../domain/types";
import {createBackendAdapter} from "../sync/adapter";
import {correctionReviewed} from "../domain/learningRules";
import {appConfig} from "../config";
import {getDb} from "../storage/db";
import {useLanguage,localizeNode,localizeCorrection} from "../i18n";
const adapter=createBackendAdapter();
const emptyRubric=()=>Object.fromEntries(rubricDimensions.map(id=>[id,"not_observed"])) as TeacherObservation["rubric"];
export function FacultyWorkspace({events,attemptId}:{events:LearningEvent[];attemptId:string}) {
 const {language}=useLanguage(); const t=(en:string,th:string)=>language==="th"?th:en;
 const [attempts,setAttempts]=useState<EvidenceAttempt[]>([]),[roster,setRoster]=useState<RosterMember[]>([]),[reviews,setReviews]=useState<TeacherObservation[]>([]);
 const [state,setState]=useState("loading"),[selected,setSelected]=useState(attemptId),[version,setVersion]=useState(events[0]?.contentVersion??latestContent.id);
 const [scope,setScope]=useState("mission-1"),[rubric,setRubric]=useState(emptyRubric),[observation,setObservation]=useState(""),[feedback,setFeedback]=useState(""),[nextStep,setNextStep]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true; if(appConfig.mode==="demo") {
   setAttempts([{attemptId,learnerId:appConfig.demoUserId,cohortId:"demo-cohort",contentVersion:events[0]?.contentVersion??latestContent.id,reportingStatus:"demo-only",events,completedAt:null}]);setRoster([{learnerId:appConfig.demoUserId,cohortId:"demo-cohort"}]);setState("demo");
   void getDb().then(db=>db.get("settings",`teacher-demo:${attemptId}`)).then(saved=>{if(active)setReviews((saved?.value??[]) as TeacherObservation[]);});
 } else void adapter.facultyWorkspace?.("summary").then(data=>{if(active){setAttempts(data.attempts);setRoster(data.roster);setReviews(data.reviews);setSelected(data.attempts[0]?.attemptId??"");setState("ready");}}).catch(()=>{if(active)setState("error");});return()=>{active=false;};},[events,attemptId]);
 const content=getContent(version), rows=attempts.filter(attempt=>attempt.contentVersion===version && ["reporting","demo-only"].includes(attempt.reportingStatus));
 const active=attempts.find(attempt=>attempt.attemptId===selected),activeContent=active?getContent(active.contentVersion):null;
 const detail=active&&activeContent?learningEvidence(activeContent,active.events):[];
 const counts=objectiveCounts(content,rows,roster.length);
 const unresolved=rows.flatMap(attempt=>learningEvidence(content,attempt.events)).filter(entry=>entry.state==="unresolved");
 const misconceptions=content.nodes.map(source=>{const node=localizeNode(source,language);return {node,count:rows.filter(attempt=>{const entry=learningEvidence(content,attempt.events).find(entry=>entry.node.id===node.id);return entry?.response&&!deriveProgress(content,attempt.events).firstCorrectNodeIds.includes(node.id);}).length,denominator:rows.filter(attempt=>attempt.events.some(event=>event.type==="core_response"&&event.nodeId===node.id)).length};});
 const exportFile=(name:string,rows:unknown[][])=>{const url=URL.createObjectURL(new Blob([csvText(rows)],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);};
 const save=async()=> {if(!active||busy)return;setBusy(true);const draft={attemptId:active.attemptId,contentVersion:active.contentVersion,scope:scope.startsWith("S")?"concept" as const:"case" as const,scopeId:scope,rubric,observation,feedback,nextStep};try{let review:TeacherObservation;if(appConfig.mode==="demo"){review={...draft,id:crypto.randomUUID(),reviewerId:"demo-faculty",reviewedAt:new Date().toISOString()};await(await getDb()).put("settings",{key:`teacher-demo:${attemptId}`,value:[...reviews,review]});}else{const result=await adapter.facultyWorkspace!("review",draft);review=result.review;}setReviews(previous=>[...previous,review]);setState(appConfig.mode==="demo"?"Demo observation saved locally — no institutional submission":"Teacher review confirmed");}catch{setState("Review not saved. Confirm service access and try again.");}finally{setBusy(false);}};
 return <section className="stack"><h1>{t("Class priorities and individual review","ประเด็นในชั้นเรียนและทบทวนรายบุคคล")}</h1><p role="status">{state}</p><p>{t("Formative evidence, not an automated judgment of competence. Missing evidence is not an incorrect answer.","หลักฐาน formative ไม่ใช่การตัดสิน competence อัตโนมัติ ข้อมูลที่ขาดไม่ใช่คำตอบผิด")}</p>
 <label>{t("Content version","Content version")}<select value={version} onChange={event=>setVersion(event.target.value)}>{[...new Set([latestContent.id,...attempts.map(attempt=>attempt.contentVersion)])].map(id=><option key={id}>{id}</option>)}</select></label>
 <div className="metrics"><article className="metric"><span>Enrolled</span><strong>{roster.length}</strong></article><article className="metric"><span>Not started</span><strong>{roster.filter(member=>!rows.some(row=>row.learnerId===member.learnerId&&row.cohortId===member.cohortId&&row.events.some(event=>event.type==="core_response"))).length}</strong></article><article className="metric"><span>Unresolved corrections</span><strong>{unresolved.length}</strong></article><article className="metric"><span>Handovers awaiting review</span><strong>{rows.reduce((sum,row)=>sum+deriveProgress(content,row.events).handoverNotes.filter(note=>note.text&&!reviews.some(review=>review.attemptId===row.attemptId&&review.scope==="case"&&review.scopeId===note.missionId && review.rubric.uncertainty_request!=="not_observed")).length,0)}</strong></article></div>
 <article className="panel staff-private"><h2>{t("Participation and submission","การเข้าร่วมและการส่งผล")}</h2><div className="table-scroll"><table><thead><tr><th>Learner</th><th>Status</th><th>First correct</th><th>Corrected</th><th>Reward</th></tr></thead><tbody>{roster.map(member=>{const row=rows.find(row=>row.learnerId===member.learnerId&&row.cohortId===member.cohortId),progress=row?deriveProgress(content,row.events):null;return <tr key={`${member.cohortId}:${member.learnerId}`}><td>{member.learnerId}</td><td>{!row||!progress?.answeredNodeIds.length?t("No received responses","ยังไม่มีคำตอบที่ส่งมา"):row.reportingStatus==="demo-only"?t("Local demo; not submitted","Demo ในเครื่อง ไม่ได้ส่งจริง"):row.completedAt?t("Confirmed complete","ยืนยันส่งครบแล้ว"):t("Received; incomplete","รับข้อมูลบางส่วนแล้ว")}</td><td>{progress?.firstCorrectNodeIds.length??0}/15</td><td>{progress?.correctedNodeIds.length??0}/15</td><td>{row?computeRewards(content,row.events).total:0}/250</td></tr>;})}</tbody></table></div></article>
 <article className="panel"><h2>{t("Objective evidence","หลักฐานตาม objective")}</h2><div className="table-scroll"><table><thead><tr><th>Objective</th><th>Observed / expected</th><th>First correct / observed</th><th>Corrected / observed</th><th>Unresolved / observed</th></tr></thead><tbody>{counts.map(row=><tr key={row.id}><td>{row.id}</td><td>{row.observed}/{row.expected}</td><td>{row.firstCorrect}/{row.observed}</td><td>{row.corrected}/{row.observed}</td><td>{row.unresolved}/{row.observed}</td></tr>)}</tbody></table></div><h3>Safety concepts</h3>{["S1","S2","S3","S4","S5","S6"].map(id=><p key={id}>{id}: resolved {rows.filter(row=>deriveProgress(content,row.events).concepts.some(concept=>concept.conceptId===id&&concept.resolved)).length}/{roster.length} enrolled · evidence available {rows.filter(row=>content.nodes.filter(node=>node.conceptIds.some(concept=>concept===id)).some(node=>row.events.some(event=>event.type==="core_response"&&event.nodeId===node.id))).length}/{roster.length}</p>)}</article>
 <article className="panel class-briefing"><h2>Class briefing · anonymous discussion priorities</h2>{misconceptions.filter(item=>item.count>0).map(({node,count,denominator})=><div key={node.id}><h3>{node.id}: {node.teaching?.objective??node.question} · {count}/{denominator} first responses need discussion</h3><p>{node.teaching?.misconception}</p><p>{node.teaching?.discussionPrompt??node.question}</p><p>{node.teaching?.suggestedFeedback}</p></div>)}{!misconceptions.some(item=>item.count>0)&&<p>No observed first-response misconceptions in this version. Missing responses remain separate.</p>}<h3>{t("Recall and compare the three handovers","ทบทวนและเปรียบเทียบ handover ทั้งสามเคส")}</h3>{content.nodes.filter(node=>node.interaction==="handover").map(source=>{const node=localizeNode(source,language);return <p key={node.id}>{node.teaching?.discussionPrompt??node.question}</p>;})}</article>
 <div className="button-row"><button className="secondary" onClick={()=>exportFile("cohort-summary.csv",[["learner","cohort","version","submission_status","answered","first_correct","corrected","reward","completed"],...roster.map(member=>{const row=rows.find(row=>row.learnerId===member.learnerId&&row.cohortId===member.cohortId);const progress=row?deriveProgress(content,row.events):null;return[member.learnerId,member.cohortId,version,row?(row.events.some(event=>!event.serverReceiptTimestamp)?"pending / demo":row.completedAt?"confirmed complete":"received incomplete"):"not started",progress?.answeredNodeIds.length??0,progress?.firstCorrectNodeIds.length??0,progress?.correctedNodeIds.length??0,row?computeRewards(content,row.events).total:0,Boolean(row?.completedAt)];})])}>Export cohort CSV</button><button className="secondary" onClick={()=>exportFile("learner-evidence.csv",[["learner","attempt","version","node","state","selected","rationale","confidence","corrections","references"],...rows.flatMap(row=>learningEvidence(content,row.events).map(entry=>[row.learnerId,row.attemptId,row.contentVersion,entry.node.id,entry.state,entry.response?.selectedOptionIds.join(";"),entry.response?.rationale,entry.response?.confidence,JSON.stringify(entry.corrections),JSON.stringify(entry.references)]))])}>Export evidence CSV</button><button className="secondary" onClick={()=>exportFile("teacher-reviews.csv",[["reviewer","time","attempt","version","scope","rubric","observation","feedback","next_step"],...reviews.map(review=>[review.reviewerId,review.reviewedAt,review.attemptId,review.contentVersion,review.scopeId,JSON.stringify(review.rubric),review.observation,review.feedback,review.nextStep])])}>Export reviews CSV</button><button className="secondary" onClick={()=>{document.body.classList.add("print-class-briefing");window.print();document.body.classList.remove("print-class-briefing");}}>Print anonymous briefing</button></div>
 <article className="panel staff-private"><h2>Individual evidence</h2><select aria-label="Learner attempt" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose an attempt</option>{attempts.map(row=><option key={row.attemptId} value={row.attemptId}>{row.learnerId} · {row.contentVersion}</option>)}</select>{detail.map(({node,response,state,corrections,references})=>{const localized=localizeNode(node,language);return <details key={node.id}><summary>{node.id} · {state}</summary><p>{localized.stem}</p><p>{localized.question}</p>{localized.options.map(option=><p key={option.id}>{response?.selectedOptionIds.includes(option.id)?"Selected → ":""}{option.text}</p>)}<p>Reason: {response?.rationale??"Not provided"}</p><p>Confidence: {response?.confidence??"Optional — not provided"}</p><p>Expected teaching point: {localized.teaching?.keyMessage??node.options.find(option=>node.correctOptionIds.includes(option.id))?.explanation}</p><p>Discussion: {localized.teaching?.discussionPrompt}</p><p>Suggested advice: {localized.teaching?.suggestedFeedback}</p><p>Corrections: {corrections.map(event=>{if(event.type!=="correction_response")return "";const retry=localizeCorrection(activeContent!.corrections.find(item=>item.id===event.correctionId)!,language);return `${retry.options.find(option=>option.id===event.selectedOptionId)?.text??event.selectedOptionId} · explanation ${correctionReviewed(active!.events,event)?"reviewed":"not acknowledged"}`;}).join("; ")||"None"}</p><p>Reference use: {references.map(event=>event.type==="resource_viewed"?`${event.resourceId} (${event.stage??"unspecified"})`:"").join("; ")||"No contextual use recorded"}</p><small>{node.teaching?.sources.join(" · ")}</small></details>;})}</article>
 {active&&<article className="panel staff-private"><h2>Teacher observation after discussion</h2><p>Staff-only. Does not change learner rewards. Free text is not automatically graded.</p><select aria-label="Review scope" value={scope} onChange={event=>setScope(event.target.value)}>{["mission-1","mission-2","mission-3","S1","S2","S3","S4","S5","S6"].map(id=><option key={id}>{id}</option>)}</select>{rubricDimensions.map(id=><label key={id}>{id.replaceAll("_"," ")}<select value={rubric[id]} onChange={event=>setRubric(previous=>({...previous,[id]:event.target.value as typeof rubricStates[number]}))}>{rubricStates.map(state=><option key={state} value={state}>{t(({not_observed:"Not observed",needs_discussion:"Needs further discussion",with_prompting:"Explains with prompting",without_prompting:"Explains without prompting"})[state],({not_observed:"ยังไม่ได้สังเกต",needs_discussion:"ต้องอภิปรายเพิ่มเติม",with_prompting:"อธิบายได้เมื่อมีคำถามนำ",without_prompting:"อธิบายได้โดยไม่ต้องชี้นำ"})[state])}</option>)}</select></label>)}<label>Observation<textarea maxLength={1500} value={observation} onChange={event=>setObservation(event.target.value)}/></label><label>Feedback<textarea maxLength={1500} value={feedback} onChange={event=>setFeedback(event.target.value)}/></label><label>Next step<textarea maxLength={1500} value={nextStep} onChange={event=>setNextStep(event.target.value)}/></label><button className="primary" disabled={busy||(!navigator.onLine&&appConfig.mode!=="demo")} onClick={save}>Save teacher observation</button>{reviews.filter(review=>review.attemptId===active.attemptId).map(review=><details key={review.id}><summary>{review.scopeId} · {review.reviewedAt} · {review.reviewerId}</summary><p>{JSON.stringify(review.rubric)}</p><p>{review.observation}</p><p>{review.feedback}</p><p>{review.nextStep}</p></details>)}</article>}
 </section>;
}
