import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import {FacultyWorkspace} from "./FacultyWorkspace";
import {learningJourney} from "../test/journeys";
const put=vi.hoisted(()=>vi.fn(async(_store:string,_value:unknown)=>undefined));
vi.mock("../storage/db",()=>({getDb:async()=>({get:async()=>undefined,put})}));
afterEach(cleanup);
describe("teacher evidence and observation",()=>{
 it("shows actual learner notes and saves a separate rubric record without changing events",async()=>{const events=learningJourney(false),snapshot=JSON.stringify(events);render(<FacultyWorkspace events={events} attemptId="attempt"/>);fireEvent.click(await screen.findByRole("button",{name:"Individual evidence"}));expect(await screen.findByRole("heading",{name:"Individual evidence"})).toBeInTheDocument();expect(screen.getAllByText(/Findings, priorities and uncertainty./).length).toBeGreaterThanOrEqual(3);fireEvent.change(screen.getByLabelText("Observation"),{target:{value:"Explained the uncertainty with prompting."}});fireEvent.click(screen.getByRole("button",{name:"Save teacher observation"}));await waitFor(()=>expect(put).toHaveBeenCalled());expect(JSON.stringify(events)).toBe(snapshot);expect(put.mock.calls.at(-1)?.[1]).toMatchObject({key:"teacher-demo:attempt"});});
 it("rejects reversed date ranges and hides export actions",async()=>{render(<FacultyWorkspace events={learningJourney(false)} attemptId="attempt"/>);fireEvent.change(await screen.findByLabelText("From date"),{target:{value:"2026-10-09"}});fireEvent.change(screen.getByLabelText("To date"),{target:{value:"2026-10-08"}});expect(screen.getByRole("alert")).toHaveTextContent("valid date range");fireEvent.click(screen.getByRole("button",{name:"Export results"}));expect(screen.queryByRole("button",{name:"Export cohort CSV"})).toBeNull();});
 it("searches learners and distinguishes no matching dates from incorrect answers",async()=>{render(<FacultyWorkspace events={learningJourney(false)} attemptId="attempt"/>);fireEvent.change(await screen.findByLabelText("Find learner"),{target:{value:"does-not-exist"}});expect(screen.queryByRole("button",{name:"Open learner"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"All dates"}));expect(await screen.findByRole("button",{name:"Open learner"})).toBeEnabled();fireEvent.click(screen.getByRole("button",{name:"Today"}));expect(screen.getByText("No matching evidence in range")).toBeInTheDocument();});
});
