import { useEffect, useMemo, useRef, useState } from "react";
import { getContent, latestContent } from "../content/registry";
import { deriveProgress } from "../domain/engine";
import { computeRewards } from "../domain/rewards";
import { learningEvidence, objectiveCounts, rubricDimensions, rubricStates, type EvidenceAttempt, type RosterMember, type TeacherObservation } from "../domain/assessment";
import { bangkokDay, reportScope, validReportRange, type ReportFilter } from "../domain/reportFilters";
import { buildTeacherExport, type ExportKind } from "./reports";
import type { LearningEvent } from "../domain/types";
import { createBackendAdapter } from "../sync/adapter";
import { correctionReviewed } from "../domain/learningRules";
import { appConfig } from "../config";
import { getDb } from "../storage/db";
import { useLanguage, localizeNode } from "../i18n";
const adapter = createBackendAdapter();
const emptyRubric = () => Object.fromEntries(rubricDimensions.map(id => [id, "not_observed"])) as TeacherObservation["rubric"];

export function FacultyWorkspace({ events, attemptId }: { events: LearningEvent[]; attemptId: string }) {
  const { language } = useLanguage(), t = (en: string, th: string) => language === "th" ? th : en;
  const [attempts, setAttempts] = useState<EvidenceAttempt[]>([]), [roster, setRoster] = useState<RosterMember[]>([]), [reviews, setReviews] = useState<TeacherObservation[]>([]);
  const linkedAttempt=new URLSearchParams(window.location.hash.split("?")[1]??"").get("attempt");
  const [state, setState] = useState("loading"), [selected, setSelected] = useState(linkedAttempt??attemptId), [tab, setTab] = useState(linkedAttempt?"individual":"overview"), [refresh, setRefresh] = useState(0);
  const [filter, setFilter] = useState<ReportFilter>({ from: "", to: "", basis: "activity", search: "", version: events[0]?.contentVersion ?? latestContent.id });
  const [scope, setScope] = useState("mission-1"), [rubric, setRubric] = useState(emptyRubric), [observation, setObservation] = useState(""), [feedback, setFeedback] = useState(""), [nextStep, setNextStep] = useState(""), [busy, setBusy] = useState(false);
  const saving = useRef(false);
  const [sheetDelivery,setSheetDelivery]=useState<{configured:boolean;pending:number;lastSuccess:string|null;error:string|null}|null>(null);
  const [sheetBusy,setSheetBusy]=useState(false),[sheetError,setSheetError]=useState("");
  useEffect(()=>{if(appConfig.mode!=="connected")return;let active=true;void adapter.sheetsStatus?.().then(status=>{if(active)setSheetDelivery(status);}).catch(()=>{if(active)setSheetError(t("Sheets status unavailable","ดูสถานะ Sheets ไม่ได้"));});return()=>{active=false;};},[refresh]);
  const queueSheets=async()=>{if(sheetBusy)return;setSheetBusy(true);setSheetError("");try{const status=await adapter.sheetsStatus?.(true);if(status)setSheetDelivery(status);}catch{setSheetError(t("Could not queue export. Student records remain saved.","ส่งออกไม่ได้ ข้อมูลนักศึกษายังถูกบันทึกไว้"));}finally{setSheetBusy(false);}};
  useEffect(() => {
    let active = true; setState("loading");
    if (appConfig.mode === "demo") {
      setAttempts([{ attemptId, learnerId: appConfig.demoUserId, cohortId: "demo-cohort", contentVersion: events[0]?.contentVersion ?? latestContent.id, reportingStatus: "demo-only", events, completedAt: null }]);
      setRoster([{ learnerId: appConfig.demoUserId, cohortId: "demo-cohort" }]); setState("demo");
      void getDb().then(db => db.get("settings", `teacher-demo:${attemptId}`)).then(saved => { if (active) setReviews((saved?.value ?? []) as TeacherObservation[]); });
    } else void adapter.facultyWorkspace?.("summary").then(data => { if (active) { setAttempts(data.attempts); setRoster(data.roster); setReviews(data.reviews); const linked=data.attempts.find(attempt=>attempt.attemptId===linkedAttempt);if(linked)setFilter(previous=>({...previous,version:linked.contentVersion}));setState("ready"); } }).catch(() => { if (active) setState("error"); });
    return () => { active = false; };
  }, [events, attemptId, refresh]);
  const rangeValid = validReportRange(filter.from, filter.to);
  const report = useMemo(() => reportScope(attempts, roster, reviews, filter), [attempts, roster, reviews, filter]);
  const content = getContent(filter.version), rows = report.rows;
  const active = report.visibleAttempts.find(a => a.attemptId === selected) ?? (linkedAttempt&&selected===linkedAttempt?undefined:report.visibleAttempts[0]);
  const activeContent = active ? getContent(active.contentVersion) : null;
  const entries = active && activeContent ? learningEvidence(activeContent, active.events) : [];
  const counts = objectiveCounts(content, rows, report.members.length);
  const unresolved = rows.flatMap(a => learningEvidence(content, a.events)).filter(e => e.state === "unresolved");
  const pendingHandovers = rows.reduce((sum, a) => sum + deriveProgress(content, a.events).handoverNotes.filter(n => n.text && !reviews.some(r => r.attemptId === a.attemptId && r.scopeId === n.missionId && r.rubric.uncertainty_request !== "not_observed")).length, 0);
  const priorities = content.nodes.map(node => ({ node, count: rows.filter(a => learningEvidence(content, a.events).some(e => e.node.id === node.id && ["corrected", "unresolved"].includes(e.state))).length, observed: rows.filter(a => a.events.some(e => e.type === "core_response" && e.nodeId === node.id)).length })).filter(item => item.count).sort((a, b) => b.count - a.count);
  useEffect(() => { setRubric(emptyRubric()); setObservation(""); setFeedback(""); setNextStep(""); setScope(activeContent?.missions[0]?.id ?? "mission-1"); }, [active?.attemptId, activeContent]);
  const patch = (data: Partial<ReportFilter>) => setFilter(previous => ({ ...previous, ...data }));
  const download = (kind: ExportKind) => {
    const file = buildTeacherExport(kind, attempts, roster, reviews, filter), url = URL.createObjectURL(new Blob([file.text], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = file.name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  const save = async () => {
    if (!active || saving.current) return;
    saving.current = true; setBusy(true);
    const draft = { attemptId: active.attemptId, contentVersion: active.contentVersion, scope: scope.startsWith("S") ? "concept" as const : "case" as const, scopeId: scope, rubric, observation, feedback, nextStep };
    try {
      let review: TeacherObservation;
      if (appConfig.mode === "demo") { review = { ...draft, id: crypto.randomUUID(), reviewerId: "demo-faculty", reviewedAt: new Date().toISOString() }; await (await getDb()).put("settings", { key: `teacher-demo:${attemptId}`, value: [...reviews, review] }); }
      else review = (await adapter.facultyWorkspace!("review", draft)).review;
      setReviews(previous => [...previous, review]); setState(appConfig.mode === "demo" ? "demo-saved" : "saved");
    } catch { setState("save-error"); } finally { saving.current = false; setBusy(false); }
  };
  const statusText: Record<string, string> = { loading: t("Loading received evidence…", "กำลังโหลดหลักฐาน…"), demo: t("Local demo — no institutional submission", "Demo ในเครื่อง ไม่ได้ส่งสถาบัน"), ready: t("Received evidence loaded", "โหลดหลักฐานแล้ว"), error: t("Evidence unavailable. Retry; empty totals are not confirmed.", "โหลดข้อมูลไม่ได้ ลองใหม่ ไม่ถือว่าคะแนนเป็นศูนย์"), saved: t("Teacher review confirmed", "ยืนยันบันทึกอาจารย์แล้ว"), "demo-saved": t("Demo observation saved locally", "บันทึก observation ในเครื่องแล้ว"), "save-error": t("Review not saved. Your draft remains here; retry when connected.", "ยังไม่บันทึก ร่างยังอยู่ ลองใหม่เมื่อเชื่อมต่อ") };
  return <section className="stack teacher-workspace">
    <header><span className="eyebrow">{t("TEACHER AREA", "สำหรับอาจารย์")}</span><h1>{t("Review your class", "ทบทวนผลนักศึกษา")}</h1><p>{t("1 Select dates · 2 Open a learner · 3 Record advice or export", "1 เลือกวันที่ · 2 เปิดนักศึกษา · 3 บันทึกคำแนะนำหรือส่งออก")}</p></header>
    <p role="status">{statusText[state]}</p>
    {appConfig.mode==="connected"&&<article className="panel"><h2>Google Sheets</h2><button className="secondary" disabled={sheetBusy} onClick={()=>void queueSheets()}>{sheetBusy?t("Queuing…","กำลังรอส่ง…"):t("Sync to Google Sheets","ส่งไป Google Sheets")}</button><p role="status">{sheetDelivery?(sheetDelivery.configured?t(`${sheetDelivery.pending} changes pending · Last delivery: ${sheetDelivery.lastSuccess??"not yet delivered"}`,`รอส่ง ${sheetDelivery.pending} รายการ · ส่งล่าสุด ${sheetDelivery.lastSuccess??"ยังไม่ได้ส่ง"}`):t("Google service account configuration required. Export requests stay queued.","ต้องตั้งค่า Google service account รายการส่งออกจะรออยู่ในระบบ")):sheetError||t("Checking delivery…","กำลังตรวจสอบ…")}</p>{sheetDelivery?.error&&<p role="alert">{sheetDelivery.error}</p>}<a href="https://docs.google.com/spreadsheets/d/1RCmIRdY8YUN3n5JlNVXn5A8X8up60bufMwt0LGkjt1E/edit" target="_blank" rel="noreferrer">{t("Open class workbook","เปิดสมุดผลชั้นเรียน")}</a></article>}
    <div className="report-filters panel">
      <label>{t("From date", "วันที่เริ่ม")}<input type="date" value={filter.from} onChange={e => patch({ from: e.target.value })} /></label>
      <label>{t("To date", "วันที่สิ้นสุด")}<input type="date" value={filter.to} onChange={e => patch({ to: e.target.value })} /></label>
      <label>{t("Date basis", "เลือกวันที่จาก")}<select value={filter.basis} onChange={e => patch({ basis: e.target.value as ReportFilter["basis"] })}><option value="activity">{t("Received activity", "กิจกรรมที่ระบบรับแล้ว")}</option><option value="completion">{t("Confirmed completion", "วันที่ยืนยันทำครบ")}</option></select></label>
      <label>{t("Find learner", "ค้นหานักศึกษา")}<input type="search" value={filter.search} onChange={e => patch({ search: e.target.value })} placeholder={t("Learner ID", "รหัสนักศึกษา")} /></label>
      <label>{t("Content version", "เวอร์ชันเนื้อหา")}<select value={filter.version} onChange={e => patch({ version: e.target.value })}>{[...new Set([latestContent.id, ...attempts.map(a => a.contentVersion), filter.version])].map(id => <option key={id}>{id}</option>)}</select></label>
      <div className="button-row"><button className="secondary" onClick={() => { const today = bangkokDay(new Date().toISOString()); patch({ from: today, to: today }); }}>{t("Today", "วันนี้")}</button><button className="secondary" onClick={() => patch({ from: bangkokDay(new Date(Date.now() - 6 * 86400000).toISOString()), to: bangkokDay(new Date().toISOString()) })}>{t("Last 7 days", "7 วันล่าสุด")}</button><button className="quiet" onClick={() => patch({ from: "", to: "", search: "" })}>{t("All dates", "ทุกวันที่")}</button><button className="quiet" onClick={() => setRefresh(n => n + 1)}>{t("Refresh evidence", "โหลดหลักฐานใหม่")}</button></div>
      <small>{t("Bangkok time. Dates select whole attempts; original answers stay together. Reviews use their own date. Practice is excluded from class totals.", "เวลา Bangkok เลือกทั้ง attempt เพื่อเก็บบริบทคำตอบ Reviews ใช้วันที่บันทึก Practice ไม่รวมผลชั้นเรียน")}</small>
    </div>
    {!rangeValid && <p role="alert">{t("Choose a valid date range; the end must not precede the start.", "วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่ม")}</p>}
    <nav className="button-row teacher-tabs" aria-label={t("Teacher sections", "ส่วนอาจารย์")}>{[["overview", t("Class summary", "สรุปชั้นเรียน")], ["individual", t("Individual evidence", "หลักฐานรายบุคคล")], ["exports", t("Export results", "ส่งออกผล")]].map(([id, label]) => <button key={id} className={tab === id ? "primary" : "secondary"} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {rangeValid && !["loading", "error"].includes(state) && tab === "overview" && <>
      <div className="metrics">{[[t("Enrolled / search match", "ลงทะเบียน / ตรงการค้นหา"), report.members.length], [t("Activity / completion in range", "กิจกรรม / ทำครบในช่วง"), rows.length], [t("Not started (all dates)", "ยังไม่เริ่ม (ทุกวันที่)"), report.notStarted], [t("Unresolved corrections", "Correction ที่ยังต้องแก้"), unresolved.length], [t("Handovers awaiting discussion", "Handover รออภิปราย"), pendingHandovers]].map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
      <article className="panel staff-private"><h2>{t("Learners", "นักศึกษา")}</h2><div className="table-scroll"><table><thead><tr>{[t("Learner", "นักศึกษา"), t("Submission", "การส่งผล"), t("First correct / received", "ถูกครั้งแรก / รับแล้ว"), t("Corrected", "แก้ไขแล้ว"), "Reward", t("Review", "ทบทวน")].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{report.members.map(m => { const row = rows.find(a => a.learnerId === m.learnerId && a.cohortId === m.cohortId), p = row ? deriveProgress(content, row.events) : null, practice = report.visibleAttempts.find(a => a.reportingStatus === "practice" && a.learnerId === m.learnerId && a.cohortId === m.cohortId); return <tr key={`${m.cohortId}:${m.learnerId}`}><td>{m.learnerId}</td><td>{row ? row.reportingStatus === "demo-only" ? t("Local demo", "Demo ในเครื่อง") : row.completedAt ? t("Confirmed complete", "ยืนยันทำครบ") : t("Received; incomplete", "รับบางส่วน") : practice ? t("Practice only", "Practice เท่านั้น") : filter.from || filter.to ? t("No matching evidence in range", "ไม่มีหลักฐานตรงช่วงวันที่") : t("No received responses", "ยังไม่มีคำตอบที่ส่งมา")}</td><td>{p ? `${p.firstCorrectNodeIds.length}/${p.answeredNodeIds.length}` : "—"}</td><td>{p?.correctedNodeIds.length ?? "—"}</td><td>{row ? computeRewards(content, row.events).total : "—"}</td><td><button className="quiet" disabled={!row && !practice} onClick={() => { setSelected((row ?? practice)!.attemptId); setTab("individual"); }}>{t("Open learner", "เปิดนักศึกษา")}</button></td></tr>; })}</tbody></table></div></article>
      <article className="panel class-briefing"><h2>{t("Discuss in class", "อภิปรายในชั้นเรียน")}</h2><p>{t("Learning evidence, not proven mastery. Missing evidence is not an incorrect answer.", "หลักฐานการเรียน ไม่รับรอง mastery ข้อมูลที่ขาดไม่ใช่คำตอบผิด")}</p>{priorities.map(({ node, count, observed }) => <div key={node.id}><h3>{node.teaching?.objective ?? node.question} · {count}/{observed}</h3><p>{node.teaching?.discussionPrompt}</p><p>{node.teaching?.suggestedFeedback}</p></div>)}{!priorities.length && <p>{t("No first-response misconceptions observed in this selection.", "ยังไม่พบ misconception จากคำตอบแรกในข้อมูลที่เลือก")}</p>}</article>
      <details className="panel"><summary>{t("Objective and safety evidence", "หลักฐาน objective และ safety")}</summary><div className="table-scroll"><table><thead><tr><th>Objective</th><th>Observed / expected</th><th>First correct / observed</th><th>Corrected / observed</th><th>Unresolved</th></tr></thead><tbody>{counts.map(r => <tr key={r.id}><td>{r.id}</td><td>{r.observed}/{r.expected}</td><td>{r.firstCorrect}/{r.observed}</td><td>{r.corrected}/{r.observed}</td><td>{r.unresolved}</td></tr>)}</tbody></table></div>{["S1", "S2", "S3", "S4", "S5", "S6"].map(id => <p key={id}>{id}: {rows.filter(a => deriveProgress(content, a.events).concepts.some(c => c.conceptId === id && c.resolved)).length}/{report.members.length} {t("enrolled resolved", "ลงทะเบียน แก้ไขแล้ว")}</p>)}</details>
      <details className="panel"><summary>{t("Clinical review notes", "หมายเหตุทบทวนเนื้อหา")}</summary>{content.nodes.filter(n => n.reviewNote).map(n => <p key={n.id}>{n.id}: {n.reviewNote}</p>)}</details>
    </>}
    {rangeValid && tab === "exports" && <article className="panel"><h2>{t("Export this date range", "ส่งออกช่วงวันที่นี้")}</h2><p>{t("CSV opens in Excel and includes your date range and content version. Automatic Google Sheets delivery is separate; check its status above.", "CSV เปิดใน Excel ได้ พร้อมช่วงวันที่และเวอร์ชันเนื้อหา การส่ง Google Sheets อัตโนมัติเป็นอีกระบบ ตรวจสถานะด้านบน")}</p><div className="button-row">{(["summary", "evidence", "reviews", "objectives"] as const).map(kind => <button className="secondary" key={kind} disabled={state === "loading" || state === "error"} onClick={() => download(kind)}>{({ summary: t("Export cohort CSV", "ส่งออกสรุป CSV"), evidence: t("Export evidence CSV", "ส่งออกหลักฐาน CSV"), reviews: t("Export reviews CSV", "ส่งออก review CSV"), objectives: t("Export objective CSV", "ส่งออก objective CSV") })[kind]}</button>)}<button className="secondary" disabled={state === "loading" || state === "error"} onClick={() => {setTab("overview");requestAnimationFrame(() => { document.body.classList.add("print-class-briefing"); window.print(); document.body.classList.remove("print-class-briefing"); }); }}>{t("Print anonymous briefing", "พิมพ์ประเด็นอภิปรายไม่ระบุตัวตน")}</button></div></article>}
    {rangeValid && tab === "individual" && <>
      <article className="panel staff-private"><h2>{t("Individual evidence", "หลักฐานรายบุคคล")}</h2><label>{t("Learner attempt", "Attempt นักศึกษา")}<select value={active?.attemptId ?? ""} onChange={e => setSelected(e.target.value)}><option value="">{t("Choose an attempt", "เลือก attempt")}</option>{report.visibleAttempts.map(a => <option key={a.attemptId} value={a.attemptId}>{a.learnerId} · {a.reportingStatus} · {a.contentVersion}</option>)}</select></label>{!active && <p>{t("No attempt matches. Try all dates or another version.", "ไม่มี attempt ตรงตัวกรอง ลองทุกวันที่หรือเวอร์ชันอื่น")}</p>}
        {entries.map(({ node, response, state: evidenceState, corrections, references }) => { const localized = localizeNode(node, language), answer = node.game?.cards.filter(card => Array.isArray(response?.gameAnswer) ? response.gameAnswer.includes(card.id) : response?.gameAnswer === card.id).map(card => card.label[language]).join("; "); return <details key={node.id}><summary>{node.id} · {({ missing: t("Missing evidence", "ยังไม่มีหลักฐาน"), first_correct: t("First correct", "ถูกครั้งแรก"), corrected: t("Corrected", "แก้ไขแล้ว"), unresolved: t("Needs correction", "ต้องแก้ไข") })[evidenceState]}</summary><p>{node.translation?.story[language] ?? localized.stem}</p><p>{node.translation?.title[language] ?? localized.question}</p><p>{t("Selected answer", "คำตอบที่เลือก")}: {answer || (node.game ? JSON.stringify(response?.gameAnswer ?? null) : localized.options.filter(o => response?.selectedOptionIds.includes(o.id)).map(o => o.text).join("; ")) || t("Not observed", "ยังไม่มีหลักฐาน")}</p><p>{t("Reason", "เหตุผล")}: {response?.rationale ?? t("Not provided", "ไม่ได้ระบุ")}</p><p>{t("Confidence", "Confidence")}: {response?.confidence ?? t("Optional — not provided", "ไม่บังคับ ไม่ได้ระบุ")}</p><p>{t("Expected teaching point", "ประเด็นสอน")}: {node.translation?.key[language] ?? localized.teaching?.keyMessage}</p><p>{t("Discussion", "คำถามอภิปราย")}: {localized.teaching?.discussionPrompt}</p><p>{t("Suggested advice", "คำแนะนำที่เสนอ")}: {localized.teaching?.suggestedFeedback}</p><p>{t("Corrections", "Corrections")}: {corrections.map(e => e.type === "correction_response" ? `${JSON.stringify(e.gameAnswer ?? e.selectedOptionId)} · ${correctionReviewed(active!.events, e) ? t("explanation reviewed", "ทบทวนแล้ว") : t("review pending", "รอทบทวน")}` : "").join("; ") || t("None", "ไม่มี")}</p><p>{t("Reference use", "การใช้บัตรอ้างอิง")}: {references.map(e => e.type === "resource_viewed" ? `${e.resourceId} (${e.stage ?? "unspecified"})` : "").join("; ") || t("No contextual use recorded", "ยังไม่มีบันทึก")}</p><small>{node.teaching?.sources.join(" · ")}</small></details>; })}
      </article>
      {active && <article className="panel staff-private"><h2>{t("Teacher observation after discussion", "บันทึกอาจารย์หลังอภิปราย")}</h2><p>{t("Staff-only. Does not change rewards. Free text is not automatically graded.", "เฉพาะอาจารย์ ไม่เปลี่ยน reward ไม่ตรวจ free text อัตโนมัติ")}</p><label>{t("Review scope", "ประเด็นทบทวน")}<select value={scope} onChange={e => setScope(e.target.value)}>{[...activeContent!.missions.map(m => m.id), "S1", "S2", "S3", "S4", "S5", "S6"].map(id => <option key={id}>{id}</option>)}</select></label>{rubricDimensions.map(id => <label key={id}>{({ clinical_interpretation: t("Clinical interpretation", "การแปลผลคลินิก"), priorities_supervised_action: t("Priorities and supervised action", "ลำดับสำคัญและ action"), uncertainty_request: t("Uncertainty and request", "ความไม่แน่ชัดและคำขอทีม") })[id]}<select value={rubric[id]} onChange={e => setRubric(previous => ({ ...previous, [id]: e.target.value as typeof rubricStates[number] }))}>{rubricStates.map(value => <option key={value} value={value}>{({ not_observed: t("Not observed", "ยังไม่ได้สังเกต"), needs_discussion: t("Needs further discussion", "ต้องอภิปรายเพิ่มเติม"), with_prompting: t("Explains with prompting", "อธิบายได้เมื่อชี้นำ"), without_prompting: t("Explains without prompting", "อธิบายได้โดยไม่ต้องชี้นำ") })[value]}</option>)}</select></label>)}<label>{t("Observation", "สิ่งที่สังเกต")}<textarea maxLength={1500} value={observation} onChange={e => setObservation(e.target.value)} /></label><label>{t("Feedback", "คำแนะนำ")}<textarea maxLength={1500} value={feedback} onChange={e => setFeedback(e.target.value)} /></label><label>{t("Next step", "ขั้นต่อไป")}<textarea maxLength={1500} value={nextStep} onChange={e => setNextStep(e.target.value)} /></label><button className="primary" disabled={busy || (!navigator.onLine && appConfig.mode !== "demo")} onClick={save}>{t("Save teacher observation", "บันทึกอาจารย์")}</button>{reviews.filter(r => r.attemptId === active.attemptId).map(r => <details key={r.id}><summary>{r.scopeId} · {new Date(r.reviewedAt).toLocaleString(language === "th" ? "th-TH" : "en-GB", { timeZone: "Asia/Bangkok" })} · {r.reviewerId}</summary><p>{JSON.stringify(r.rubric)}</p><p>{r.observation}</p><p>{r.feedback}</p><p>{r.nextStep}</p></details>)}</article>}
    </>}
  </section>;
}
