import {beforeEach,describe,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({invoke:vi.fn(),signInWithOtp:vi.fn(),authCallback:null as null|((event:string,session:unknown)=>void),unsubscribe:vi.fn()}));
vi.mock("@supabase/supabase-js",()=>({createClient:()=>({functions:{invoke:mocks.invoke},auth:{signInWithOtp:mocks.signInWithOtp,getSession:async()=>({data:{session:{user:{id:"learner"}}}}),onAuthStateChange:(callback:typeof mocks.authCallback)=>{mocks.authCallback=callback;return{data:{subscription:{unsubscribe:mocks.unsubscribe}}};}}})}));
import {SupabaseBackendAdapter} from "./adapter";
import type {LearningEvent} from "../domain/types";
const queue=(count:number)=>Array.from({length:count},(_,index)=>({type:"resource_viewed",eventId:`event-${index}`,attemptId:"attempt",learnerId:"learner",contentVersion:"ptd-learning-draft-2026-10-03",clientSequence:index+1,clientTimestamp:"2026-10-03T00:00:00Z",serverReceiptTimestamp:null,resourceId:"R1"} as LearningEvent));
describe("submission transport",()=>{
 it("sign-in uses an existing enrolled account, not public automatic signup",async()=>{mocks.signInWithOtp.mockResolvedValue({error:null});await new SupabaseBackendAdapter("url","key").signIn("student@example.edu");expect(mocks.signInWithOtp).toHaveBeenCalledWith({email:"student@example.edu",options:{emailRedirectTo:window.location.origin,shouldCreateUser:false}});});
 beforeEach(()=>{mocks.invoke.mockReset();mocks.unsubscribe.mockReset();});
 it("submits large queues in order within endpoint limits",async()=>{mocks.invoke.mockImplementation(async(name,{body})=>name==="start-attempt"?{data:{},error:null}:{data:{acknowledgments:body.events.map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]},error:null});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(251));expect(result.acknowledgments).toHaveLength(251);expect(mocks.invoke.mock.calls.filter(([name])=>name==="sync-events").map(([,args])=>args.body.events.length)).toEqual([100,100,51]);});
 it("keeps sending later batches after a rejected event",async()=>{mocks.invoke.mockImplementation(async(name,{body})=>name==="start-attempt"?{data:{},error:null}:{data:{acknowledgments:body.events.slice(1).map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[{eventId:body.events[0].eventId,reason:"invalid"}]},error:null});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(150));expect(result.rejected).toHaveLength(2);expect(result.acknowledgments).toHaveLength(148);expect(result.retryable).toHaveLength(0);});
 it("preserves accepted records when a later batch fails",async()=>{let index=0;mocks.invoke.mockImplementation(async(name,{body})=>{if(name==="start-attempt")return{data:{},error:null};if(index++===1)return{error:new Error("network"),data:null};return{data:{acknowledgments:body.events.map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]},error:null};});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(251));expect(result.acknowledgments).toHaveLength(100);expect(result.retryable).toHaveLength(151);});
 it("recovers a completion receipt independently of the event queue",async()=>{const receipt={status:"server_confirmed",completedAt:"2026-10-03T00:00:00Z",reportingAttemptId:"attempt"};mocks.invoke.mockResolvedValue({data:{completionReceipt:receipt},error:null});const adapter=new SupabaseBackendAdapter("url","key");expect(await adapter.recoverCompletion("attempt")).toEqual(receipt);expect(await adapter.recoverCompletion("attempt")).toEqual(receipt);expect(mocks.invoke.mock.calls[0][0]).toBe("completion-status");});
 it("propagates authentication changes and removes its listener",async()=>{const callback=vi.fn(),adapter=new SupabaseBackendAdapter("url","key");const unsubscribe=adapter.onAuthChange(callback);await adapter.currentUserId();mocks.authCallback?.("SIGNED_OUT",null);mocks.authCallback?.("SIGNED_IN",{user:{id:"new"}});expect(callback.mock.calls).toEqual([[null],["new"]]);unsubscribe();expect(mocks.unsubscribe).toHaveBeenCalledOnce();});
});
