import {beforeEach,describe,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({invoke:vi.fn(),getSession:vi.fn(),createClient:vi.fn(),signOut:vi.fn(),signInWithOtp:vi.fn(),authCallback:null as null|((event:string,session:unknown)=>void),unsubscribe:vi.fn()}));
vi.mock("@supabase/supabase-js",()=>({createClient:(...args:unknown[])=>{mocks.createClient(...args);return{functions:{invoke:mocks.invoke},auth:{signOut:mocks.signOut,signInWithOtp:mocks.signInWithOtp,getSession:mocks.getSession,onAuthStateChange:(callback:typeof mocks.authCallback)=>{mocks.authCallback=callback;return{data:{subscription:{unsubscribe:mocks.unsubscribe}}};}}};}}));
import {SupabaseBackendAdapter} from "./adapter";
import {saveSession} from "../storage/session";
import type {LearningEvent} from "../domain/types";
const queue=(count:number)=>Array.from({length:count},(_,index)=>({type:"resource_viewed",eventId:`event-${index}`,attemptId:"attempt",learnerId:"learner",contentVersion:"ptd-learning-draft-2026-10-03",clientSequence:index+1,clientTimestamp:"2026-10-03T00:00:00Z",serverReceiptTimestamp:null,resourceId:"R1"} as LearningEvent));
describe("submission transport",()=>{
 it("registers the parent before a practice attempt and passes its actual kind",async()=>{saveSession("connected:practice-test",{attemptId:"attempt",contentVersion:"ptd-learning-draft-2026-10-03",kind:"practice",originalAttemptId:"original"});mocks.invoke.mockImplementation(async(name,{body})=>({data:name==="sync-events"?{acknowledgments:body.events.map((e:LearningEvent)=>({eventId:e.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]}:{},error:null}));await new SupabaseBackendAdapter("url","key").syncEvents(queue(1));const starts=mocks.invoke.mock.calls.filter(([name])=>name==="start-attempt").map(([,options])=>options.body);expect(starts[0]).toMatchObject({attemptId:"original",kind:"initial"});expect(starts[1]).toMatchObject({attemptId:"attempt",kind:"practice",originalAttemptId:"original"});localStorage.removeItem("ptd-session:attempt");});
 it("signs out only this browser and propagates service failures",async()=>{const adapter=new SupabaseBackendAdapter("url","key");mocks.signOut.mockResolvedValueOnce({error:null});await adapter.signOut();expect(mocks.signOut).toHaveBeenLastCalledWith({scope:"local"});mocks.signOut.mockResolvedValueOnce({error:new Error("offline")});await expect(adapter.signOut()).rejects.toThrow("offline");});
 it("sign-in uses an existing enrolled account, not public automatic signup",async()=>{mocks.signInWithOtp.mockResolvedValue({error:null});await new SupabaseBackendAdapter("url","key").signIn("student@example.edu");expect(mocks.signInWithOtp).toHaveBeenCalledWith({email:"student@example.edu",options:{emailRedirectTo:window.location.origin,shouldCreateUser:false}});});
 beforeEach(()=>{mocks.invoke.mockReset();mocks.unsubscribe.mockReset();mocks.getSession.mockReset().mockResolvedValue({data:{session:{user:{id:"learner"},access_token:"test-user-jwt"}},error:null});});
 it("shares one Auth client across learner, faculty and ranking adapters",async()=>{const before=mocks.createClient.mock.calls.length;await Promise.all([1,2,3].map(()=>new SupabaseBackendAdapter("shared-client-test","public-key").currentUserId()));expect(mocks.createClient.mock.calls.length-before).toBe(1);});
 it("uses the current user token on every protected request",async()=>{mocks.invoke.mockImplementation(async(name,{body})=>({data:name==="sync-events"?{acknowledgments:body.events.map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]}:name==="cohort-leaderboard"?{rows:[]}:name==="completion-status"?{completionReceipt:null}:{},error:null}));const adapter=new SupabaseBackendAdapter("url","key");await adapter.syncEvents(queue(1));await adapter.facultyWorkspace("context");await adapter.loadLeaderboard("version");await adapter.recoverCompletion("attempt");expect(mocks.invoke.mock.calls.map(([name])=>name)).toEqual(["start-attempt","sync-events","faculty-workspace","cohort-leaderboard","completion-status"]);for(const [,options]of mocks.invoke.mock.calls)expect(options.headers).toEqual({Authorization:"Bearer test-user-jwt"});mocks.getSession.mockResolvedValue({data:{session:{user:{id:"learner"},access_token:"refreshed-test-jwt"}},error:null});await adapter.recoverCompletion("attempt");expect(mocks.invoke.mock.lastCall?.[1].headers.Authorization).toBe("Bearer refreshed-test-jwt");});
 it("never calls a protected endpoint without a session",async()=>{mocks.getSession.mockResolvedValue({data:{session:null},error:null});const adapter=new SupabaseBackendAdapter("url","key");await expect(adapter.syncEvents(queue(1))).rejects.toThrow("Sign in again");await expect(adapter.facultyWorkspace("context")).rejects.toThrow("Sign in again");await expect(adapter.loadLeaderboard("version")).rejects.toThrow("Sign in again");await expect(adapter.recoverCompletion("attempt")).rejects.toThrow("Sign in again");expect(mocks.invoke).not.toHaveBeenCalled();});
 it("discards a protected response after account switch or sign-out",async()=>{
  mocks.invoke.mockResolvedValue({data:{authorized:true},error:null});
  mocks.getSession.mockResolvedValueOnce({data:{session:{user:{id:"teacher"},access_token:"teacher-token"}},error:null}).mockResolvedValueOnce({data:{session:{user:{id:"learner"},access_token:"learner-token"}},error:null});
  await expect(new SupabaseBackendAdapter("url","key").facultyWorkspace("context")).rejects.toThrow("Account changed");
  mocks.getSession.mockResolvedValueOnce({data:{session:{user:{id:"teacher"},access_token:"teacher-token"}},error:null}).mockResolvedValueOnce({data:{session:null},error:null});
  await expect(new SupabaseBackendAdapter("url","key").facultyWorkspace("context")).rejects.toThrow("Account changed");
 });
 it("does not submit when Auth reports a session recovery error",async()=>{mocks.getSession.mockResolvedValue({data:{session:{access_token:"test-token"}},error:new Error("session unavailable")});await expect(new SupabaseBackendAdapter("url","key").syncEvents(queue(1))).rejects.toThrow("Sign in again");expect(mocks.invoke).not.toHaveBeenCalled();});
 it("submits large queues in order within endpoint limits",async()=>{mocks.invoke.mockImplementation(async(name,{body})=>name==="start-attempt"?{data:{},error:null}:{data:{acknowledgments:body.events.map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]},error:null});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(251));expect(result.acknowledgments).toHaveLength(251);expect(mocks.invoke.mock.calls.filter(([name])=>name==="sync-events").map(([,args])=>args.body.events.length)).toEqual([100,100,51]);});
 it("keeps sending later batches after a rejected event",async()=>{mocks.invoke.mockImplementation(async(name,{body})=>name==="start-attempt"?{data:{},error:null}:{data:{acknowledgments:body.events.slice(1).map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[{eventId:body.events[0].eventId,reason:"invalid"}]},error:null});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(150));expect(result.rejected).toHaveLength(2);expect(result.acknowledgments).toHaveLength(148);expect(result.retryable).toHaveLength(0);});
 it("preserves accepted records when a later batch fails",async()=>{let index=0;mocks.invoke.mockImplementation(async(name,{body})=>{if(name==="start-attempt")return{data:{},error:null};if(index++===1)return{error:new Error("network"),data:null};return{data:{acknowledgments:body.events.map((event:LearningEvent)=>({eventId:event.eventId,serverReceiptTimestamp:"received"})),retryable:[],rejected:[]},error:null};});const result=await new SupabaseBackendAdapter("url","key").syncEvents(queue(251));expect(result.acknowledgments).toHaveLength(100);expect(result.retryable).toHaveLength(151);});
 it("recovers a completion receipt independently of the event queue",async()=>{const receipt={status:"server_confirmed",completedAt:"2026-10-03T00:00:00Z",reportingAttemptId:"attempt"};mocks.invoke.mockResolvedValue({data:{completionReceipt:receipt},error:null});const adapter=new SupabaseBackendAdapter("url","key");expect(await adapter.recoverCompletion("attempt")).toEqual(receipt);expect(await adapter.recoverCompletion("attempt")).toEqual(receipt);expect(mocks.invoke.mock.calls[0][0]).toBe("completion-status");});
 it("propagates authentication changes and removes its listener",async()=>{const callback=vi.fn(),adapter=new SupabaseBackendAdapter("url","key");const unsubscribe=adapter.onAuthChange(callback);await adapter.currentUserId();mocks.authCallback?.("SIGNED_OUT",null);mocks.authCallback?.("SIGNED_IN",{user:{id:"new"}});expect(callback.mock.calls).toEqual([[null],["new"]]);unsubscribe();expect(mocks.unsubscribe).toHaveBeenCalledOnce();});
});
