// Minimal Google Sheets client for a service account, using only Web Crypto (no SDK, no key on the client).
// Secrets live only in Supabase: `supabase secrets set GOOGLE_SA_JSON='<service-account json>' SHEET_ID='<spreadsheet id>'`.
// The spreadsheet is shared with the service account's e-mail as Editor; nothing is ever public.

type ServiceAccount = { client_email: string; private_key: string; token_uri?: string };

const encoder = new TextEncoder();
const base64url = (bytes: Uint8Array | string) => {
  const raw = typeof bytes === "string" ? encoder.encode(bytes) : bytes;
  let binary = "";
  for (const byte of raw) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
};

async function signingKey(pem: string): Promise<CryptoKey> {
  const body = pem.replace(/-----(BEGIN|END) PRIVATE KEY-----/g, "").replace(/\s+/g, "");
  const der = Uint8Array.from(atob(body), (char) => char.charCodeAt(0));
  return crypto.subtle.importKey("pkcs8", der, { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]);
}

export async function accessToken(account: ServiceAccount, now = Math.floor(Date.now() / 1000)): Promise<string> {
  const tokenUri = account.token_uri ?? "https://oauth2.googleapis.com/token";
  const header = base64url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claims = base64url(JSON.stringify({ iss: account.client_email, scope: "https://www.googleapis.com/auth/spreadsheets", aud: tokenUri, iat: now, exp: now + 600 }));
  const signature = new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5", await signingKey(account.private_key), encoder.encode(`${header}.${claims}`)));
  const response = await fetch(tokenUri, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion: `${header}.${claims}.${base64url(signature)}` }),
  });
  if (!response.ok) throw new Error(`Google sign-in failed (${response.status})`);
  return (await response.json()).access_token as string;
}

export class SheetsClient {
  constructor(private spreadsheetId: string, private token: string) {}
  private async call(path: string, init: RequestInit = {}) {
    const response = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(this.spreadsheetId)}${path}`, {
      ...init,
      headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json", ...(init.headers ?? {}) },
    });
    if (!response.ok) throw new Error(`Google Sheets request failed (${response.status})`);
    return response.json();
  }
  async read(ranges: string[]): Promise<unknown[][][]> {
    const query = ranges.map((range) => `ranges=${encodeURIComponent(range)}`).join("&");
    const data = await this.call(`/values:batchGet?${query}&valueRenderOption=UNFORMATTED_VALUE`);
    return (data.valueRanges ?? []).map((range: { values?: unknown[][] }) => range.values ?? []);
  }
  async clear(ranges: string[]) {
    await this.call("/values:batchClear", { method: "POST", body: JSON.stringify({ ranges }) });
  }
  /** USER_ENTERED so dates, numbers and formulas (e.g. the p-value TDIST) are interpreted by Sheets. */
  async write(data: Array<{ range: string; values: unknown[][] }>) {
    await this.call("/values:batchUpdate", { method: "POST", body: JSON.stringify({ valueInputOption: "USER_ENTERED", data }) });
  }
  async append(range: string, values: unknown[][]) {
    if (!values.length) return;
    await this.call(`/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`, { method: "POST", body: JSON.stringify({ values }) });
  }
}

/** Text that Sheets would treat as a formula is prefixed with an apostrophe (except our own computed formulas). */
export function safeCell(value: unknown, allowFormula = false): unknown {
  if (typeof value !== "string") return value ?? "";
  // Only formulas generated by our own export (the p-value column) may pass through.
  if (allowFormula && /^=IF\(J\d+>0,TDIST\(ABS\(I\d+\),J\d+,2\),""\)$/.test(value)) return value;
  return /^[\s]*[=+\-@\t\r]/.test(value) ? `'${value}` : value;
}
