import { pelvicTraumaContent as legacy } from "./content.v1";
import type { Asset, ContentVersion, Node, Option } from "../domain/types";
import { contentVersionSchema, validateContentLinks } from "../domain/schema";

export const REVISION_ID = "ptd-caseflow-draft-2026-10-02";
type Copy = { phase: string; stem: string; question: string; choices: [string, string, string]; reasons: [string, string, string]; facts: string[]; retry: string; retryChoices: [string, string, string]; retryReasons: [string, string, string] };
type Revision = { id: string; key: number; retryKey: number; en: Copy; th: Copy; visuals?: Node["visuals"] };
export const revisions: Revision[] = [
  { id: "M1N1", key: 1, retryKey: 2,
    en: { phase: "Arrival", stem: "A 24-year-old motorcyclist arrives 35 minutes after injury. The airway is patent; pelvic pain and cool peripheries accompany HR 132/min and BP 82/50 mmHg. Your senior asks for the immediate concern.", question: "What would you tell your senior now?", choices: ["Pelvic pain needs assessment; first establish the fracture pattern.", "Possible major haemorrhage needs urgent team assessment and support.", "A pelvic injury is likely; first establish whether the ring is stable."], reasons: ["The fracture pattern matters, but must not delay a response to concerning physiology.", "Hypotension, tachycardia and cool peripheries raise an urgent haemorrhage concern; the source is not yet established.", "Mechanical stability is a separate judgment and does not resolve the immediate physiological threat."], facts: ["High-energy injury", "Airway patent", "Pelvic pain and cool peripheries"], retry: "Your senior asks why this patient needs urgent support before the fracture is classified.", retryChoices: ["The mechanism establishes a mechanically unstable fracture.", "Pelvic pain establishes the pelvis as the only bleeding source.", "The current physiology raises concern for major haemorrhage."], retryReasons: ["Mechanism alone does not establish the fracture's mechanical stability.", "Pain does not establish the only bleeding source.", "The current observations justify escalation while sources are assessed."] },
    th: { phase: "รับผู้ป่วย", stem: "ผู้ป่วยอายุ 24 ปีจากอุบัติเหตุจักรยานยนต์ มาถึงหลังบาดเจ็บ 35 นาที Airway ยัง patent มี pelvic pain และปลายมือเท้าเย็น HR 132/min, BP 82/50 mmHg อาจารย์ถามถึงข้อกังวลเร่งด่วน", question: "คุณจะรายงานอาจารย์อย่างไรตอนนี้?", choices: ["ต้องประเมิน pelvic pain โดยระบุ fracture pattern ก่อน", "สงสัย major haemorrhage ต้องเรียกทีมช่วยประเมินเร่งด่วน", "สงสัย pelvic injury โดยยืนยัน ring stability ก่อน"], reasons: ["Fracture pattern สำคัญ แต่ไม่ควรทำให้การดูแล physiology ที่น่ากังวลล่าช้า", "Hypotension, tachycardia และปลายมือเท้าเย็นทำให้สงสัย haemorrhage เร่งด่วน โดยยังไม่ทราบแหล่งเลือดออก", "Mechanical stability เป็นอีกการประเมินหนึ่ง และไม่ตอบภัยคุกคามทาง physiology ตอนนี้"], facts: ["High-energy injury", "Airway patent", "Pelvic pain และปลายมือเท้าเย็น"], retry: "อาจารย์ถามว่าทำไมต้องเรียกทีมช่วยก่อนจำแนก fracture", retryChoices: ["กลไกยืนยันว่า fracture mechanically unstable", "Pelvic pain ยืนยันว่า pelvis เป็นแหล่งเลือดออกเดียว", "Physiology ปัจจุบันทำให้สงสัย major haemorrhage"], retryReasons: ["กลไกอย่างเดียวไม่ยืนยัน mechanical stability", "อาการปวดไม่ยืนยันแหล่งเลือดออกเพียงแห่งเดียว", "ข้อมูลปัจจุบันเพียงพอให้ escalation พร้อมค้นหาแหล่งเลือดออก"] }
  },
  { id: "M1N2", key: 2, retryKey: 0,
    en: { phase: "Team response", stem: "BP remains 82/50 mmHg. The senior trauma team is responding while the primary survey continues. You are asked to communicate the immediate priorities.", question: "Which priorities would you communicate?", choices: ["Complete the pelvic imaging review, then activate haemorrhage support.", "Clarify mechanical stability, then decide whether support is needed.", "Continue assessment and resuscitation with indicated stabilization."], reasons: ["Waiting for imaging can delay necessary support in ongoing compromise.", "Physiological compromise already requires a response; repeated provocative testing is not a student task.", "Primary survey, trauma/haemorrhage support and indicated temporary stabilization proceed together."], facts: ["Concerning physiology persists", "Other threats and bleeding sites remain under assessment"], retry: "The team is mobilizing. Which tasks should continue together?", retryChoices: ["Primary survey, indicated resuscitation and temporary stabilization.", "Imaging classification and a pause in the resuscitation response.", "Mechanical stability testing before further trauma-team support."], retryReasons: ["Assessment and treatment proceed in parallel under the team.", "Classification does not justify pausing urgent care.", "This delays care and introduces unnecessary provocative testing."] },
    th: { phase: "ทีมเข้าช่วย", stem: "BP ยัง 82/50 mmHg ทีมอาวุโสกำลังเข้าช่วยขณะทำ primary survey ต่อ คุณได้รับหน้าที่สื่อสารลำดับความสำคัญ", question: "คุณจะสื่อสารสิ่งที่ต้องทำอย่างไร?", choices: ["อ่าน pelvic imaging ให้เสร็จก่อนเรียก haemorrhage support", "ยืนยัน mechanical stability ก่อนตัดสินใจเรียกทีมช่วย", "ประเมินและ resuscitation ต่อพร้อม stabilization ที่มีข้อบ่งชี้"], reasons: ["การรอ imaging อาจทำให้การช่วยผู้ป่วยที่ยัง compromise ล่าช้า", "Physiology บ่งว่าต้องดูแลแล้ว การทำ provocative testing ซ้ำไม่ใช่หน้าที่นักศึกษา", "Primary survey, trauma/haemorrhage support และ temporary stabilization ทำคู่ขนานกันได้"], facts: ["Physiology ยังน่ากังวล", "กำลังประเมินภัยคุกคามและแหล่งเลือดออกอื่น"], retry: "ขณะทีมเข้าช่วย งานใดควรทำต่อพร้อมกัน?", retryChoices: ["Primary survey, resuscitation และ temporary stabilization ที่มีข้อบ่งชี้", "จำแนก imaging พร้อมพักการ resuscitation", "ทดสอบ mechanical stability ก่อนเรียกทีม trauma เพิ่ม"], retryReasons: ["ทีมทำ assessment และ treatment คู่ขนานกัน", "Classification ไม่ใช่เหตุให้หยุดการดูแลเร่งด่วน", "ทำให้การดูแลล่าช้าและเพิ่ม provocative testing ที่ไม่จำเป็น"] }
  },
  { id: "M1N3", key: 0, retryKey: 1, visuals: [{ assetId: "V2_BINDER", placement: "question", role: "teaching_example" }],
    en: { phase: "Temporary stabilization", stem: "The team considers a binder indicated under the local pathway. A training-manikin photograph shows the landmark. Your role is to recognize the position and request trained review.", question: "Which landmark should you confirm with the team?", choices: ["Centre the binder over the greater trochanters.", "Centre the binder over the iliac crests.", "Centre the binder at the umbilical level."], reasons: ["The intended centre is at the greater-trochanter level; application is performed by trained staff.", "The iliac crests are too high for the intended binder centre.", "The umbilicus is too high for the intended binder centre."], facts: ["Binder indicated by the treating team", "Landmark recognition only"], retry: "The binder is described as centred at the waist. What should you request?", retryChoices: ["Confirm the waist position while waiting for the next image.", "Ask trained staff to review the greater-trochanter position.", "Ask trained staff to move the centre to the iliac crests."], retryReasons: ["A high position should be reviewed while urgent care continues.", "Recognize the intended landmark and request trained correction.", "The iliac crests remain too high."] },
    th: { phase: "Temporary stabilization", stem: "ทีมเห็นว่ามีข้อบ่งชี้ใช้ binder ตาม local pathway ภาพหุ่นฝึกแสดง landmark หน้าที่คุณคือระบุตำแหน่งและขอให้ผู้มีทักษะทบทวน", question: "คุณควรยืนยัน landmark ใดกับทีม?", choices: ["กึ่งกลาง binder อยู่ระดับ greater trochanters", "กึ่งกลาง binder อยู่ระดับ iliac crests", "กึ่งกลาง binder อยู่ระดับ umbilicus"], reasons: ["ตำแหน่งที่ต้องการคือ greater trochanters โดยผู้มีทักษะเป็นผู้ใส่", "Iliac crests สูงกว่าตำแหน่งกึ่งกลางที่ต้องการ", "Umbilicus สูงกว่าตำแหน่งกึ่งกลางที่ต้องการ"], facts: ["ทีมรักษาพิจารณาข้อบ่งชี้ binder แล้ว", "ประเมินการระบุ landmark เท่านั้น"], retry: "มีรายงานว่า binder อยู่ระดับเอว คุณควรขออย่างไร?", retryChoices: ["ยืนยันตำแหน่งเอวระหว่างรอภาพถัดไป", "ขอผู้มีทักษะทบทวนตำแหน่ง greater trochanters", "ขอผู้มีทักษะเลื่อนกึ่งกลางไป iliac crests"], retryReasons: ["ควรทบทวนตำแหน่งที่สูงขณะดูแลเร่งด่วนต่อ", "ระบุ landmark ที่ถูกและขอให้ผู้มีทักษะช่วยแก้", "Iliac crests ยังสูงเกินไป"] }
  },
  { id: "M1N5", key: 2, retryKey: 0,
    en: { phase: "Reassessment", stem: "Initial measures are underway. The supplied observation trend shows a brief BP rise followed by another fall. Assessment for other bleeding sources continues.", question: "What would you report about this response?", choices: ["The brief rise supports moving to routine imaging next.", "The recurrent fall identifies a pelvic arterial bleeding source.", "The transient response needs reassessment and escalation."], reasons: ["A brief improvement does not establish sustained stability for routine transport.", "The trend does not prove a pelvic source or a particular vessel.", "Report the recurrent compromise, current status and response while the team reassesses."], facts: ["BP rises briefly, then falls", "Other bleeding sources are still being assessed"], retry: "The senior asks whether the brief BP rise proves that bleeding is controlled.", retryChoices: ["No; recurrent compromise requires continued reassessment.", "Yes; an initial rise establishes a sustained response.", "It proves a pelvic vessel is the only remaining source."], retryReasons: ["A transient response is not proof of control.", "The subsequent fall contradicts sustained improvement.", "The observations cannot establish one bleeding source."] },
    th: { phase: "ประเมินซ้ำ", stem: "เริ่มการดูแลเบื้องต้นแล้ว แนวโน้มที่กำหนดในเคสแสดง BP สูงขึ้นชั่วครู่แล้วลดอีก ทีมยังประเมินแหล่งเลือดออกอื่น", question: "คุณจะรายงาน response นี้อย่างไร?", choices: ["BP ที่สูงชั่วครู่สนับสนุนให้ไป routine imaging ต่อ", "BP ที่ลดอีกระบุว่าเลือดออกจาก pelvic artery", "Transient response ต้อง reassessment และ escalation"], reasons: ["การดีขึ้นชั่วครู่ไม่ยืนยัน sustained stability สำหรับ routine transport", "แนวโน้มไม่ยืนยัน pelvic source หรือ vessel ใด", "รายงาน compromise ที่กลับมา สถานะปัจจุบันและ response ให้ทีมประเมินซ้ำ"], facts: ["BP สูงชั่วครู่แล้วลดอีก", "ยังประเมินแหล่งเลือดออกอื่น"], retry: "อาจารย์ถามว่า BP ที่สูงขึ้นชั่วครู่ยืนยันว่าควบคุมเลือดออกแล้วหรือไม่", retryChoices: ["ยังไม่ยืนยัน เพราะ compromise กลับมาและต้องประเมินต่อ", "ยืนยัน เพราะ BP ที่สูงครั้งแรกคือ sustained response", "ยืนยันว่ามีเพียง pelvic vessel ที่ยังเลือดออก"], retryReasons: ["Transient response ไม่ใช่หลักฐานว่าควบคุมเลือดออกได้", "BP ที่ลดตามมาไม่ใช่ sustained improvement", "ข้อมูลนี้ไม่ระบุแหล่งเลือดออกแห่งเดียว"] }
  },
  { id: "M1N4", key: 0, retryKey: 2,
    en: { phase: "Next-care planning", stem: "BP remains low after the transient response. CT requires transport away from resuscitation. Your senior asks what should guide the immediate plan in this setting.", question: "Which plan would you discuss with your senior?", choices: ["Continue resuscitation and urgent haemorrhage-control planning.", "Prioritize remote CT before reviewing the ongoing response.", "Wait for sustained observations before further senior planning."], reasons: ["Ongoing compromise requires treatment and urgent senior planning; imaging depends on response and capability.", "Remote CT may introduce delay and loss of resuscitation capability in this stated setting.", "Senior planning should continue during reassessment rather than wait for spontaneous improvement."], facts: ["BP remains low", "CT is remote from resuscitation"], retry: "Your patient remains compromised; another patient has sustained monitored stability and safe CT access. What explains different imaging plans?", retryChoices: ["The fracture label determines timing for both patients.", "The availability of CT determines timing regardless of response.", "Physiology, response and safe capability determine timing."], retryReasons: ["The label does not replace physiological assessment.", "Availability alone does not establish safe access.", "Imaging and treatment are coordinated for the patient's current setting."] },
    th: { phase: "วางแผนดูแลต่อ", stem: "หลัง transient response BP ยังต่ำ การไป CT ต้องออกจาก resuscitation area อาจารย์ถามว่าแผนทันทีควรยึดอะไรในบริบทนี้", question: "คุณจะหารือแผนใดกับอาจารย์?", choices: ["ทำ resuscitation ต่อพร้อมวางแผน haemorrhage control เร่งด่วน", "ไป CT ที่อยู่ไกลก่อนทบทวน response ที่ยังน่ากังวล", "รอ observations คงที่ก่อนวางแผนกับทีมอาวุโสต่อ"], reasons: ["Ongoing compromise ต้องรักษาและวางแผนเร่งด่วน ส่วน imaging ขึ้นกับ response และ capability", "CT ที่อยู่ไกลอาจทำให้ล่าช้าและลดความพร้อม resuscitation ในบริบทนี้", "ควรวางแผนกับทีมอาวุโสระหว่างประเมินซ้ำ ไม่รอให้ดีขึ้นเอง"], facts: ["BP ยังต่ำ", "CT อยู่ไกลจาก resuscitation"], retry: "ผู้ป่วยรายนี้ยัง compromise แต่อีกรายมี sustained monitored stability และเข้า CT ได้ปลอดภัย อะไรทำให้แผน imaging ต่างกัน?", retryChoices: ["Fracture label กำหนด timing ของทั้งคู่", "มี CT ก็ไปได้โดยไม่ต้องดู response", "Physiology, response และ safe capability กำหนด timing"], retryReasons: ["Label ไม่แทนการประเมิน physiology", "ความพร้อม CT อย่างเดียวไม่ยืนยันความปลอดภัย", "ประสาน imaging กับ treatment ตามบริบทปัจจุบัน"] }
  },
  { id: "M1N6", key: 1, retryKey: 0,
    en: { phase: "Urgent handover", stem: "Urgent care continues. The receiving team needs the mechanism, physiological trend, actions and response, remaining concerns and a clear request.", question: "Which opening best supports the urgent handover?", choices: ["High-energy pelvic injury; please classify the fracture before review.", "Recurrent hypotension after initial measures; urgent trauma review requested.", "Pelvic pain after a collision; please advise when imaging is complete."], reasons: ["A classification request alone omits the current threat and urgency.", "Lead with recurrent compromise and the urgent request, then add the mechanism, actions, response and uncertainties.", "This postpones review and omits the concerning physiological trend."], facts: ["Transient response with recurrent hypotension", "Mechanism, actions and response are available"], retry: "The draft referral describes the fracture but omits the recurrent hypotension. What would you add?", retryChoices: ["Current trend, actions and response, and the urgent request.", "The fracture subtype and a request for routine imaging advice.", "The initial mechanism and a request to await final classification."], retryReasons: ["These details communicate the immediate problem and requested help.", "This still omits the physiological threat.", "Waiting for classification does not address urgent care."] },
    th: { phase: "ส่งต่อข้อมูลเร่งด่วน", stem: "ทีมยังดูแลเร่งด่วน ทีมรับต่อจำเป็นต้องทราบกลไก แนวโน้ม physiology การดูแลและ response ข้อกังวลที่เหลือ และคำขอชัดเจน", question: "คำเปิด handover ใดช่วยทีมรับต่อที่สุด?", choices: ["High-energy pelvic injury ขอจำแนก fracture ก่อน review", "Hypotension กลับมาหลัง initial measures ขอ urgent trauma review", "Pelvic pain หลัง collision ขอคำแนะนำเมื่อ imaging เสร็จ"], reasons: ["การขอ classification อย่างเดียวไม่สื่อภัยคุกคามและความเร่งด่วน", "เริ่มด้วย compromise ที่กลับมาและคำขอเร่งด่วน แล้วเติมกลไก actions, response และ uncertainty", "ทำให้ review ล่าช้าและไม่บอกแนวโน้ม physiology ที่น่ากังวล"], facts: ["Transient response ตามด้วย recurrent hypotension", "มีข้อมูลกลไก actions และ response"], retry: "Referral ระบุ fracture แต่ไม่กล่าวถึง hypotension ที่กลับมา คุณจะเติมอะไร?", retryChoices: ["Trend ปัจจุบัน actions, response และคำขอเร่งด่วน", "Fracture subtype และขอ routine imaging advice", "กลไกแรกเริ่มและขอรอ final classification"], retryReasons: ["ข้อมูลเหล่านี้สื่อปัญหาตอนนี้และความช่วยเหลือที่ต้องการ", "ยังไม่สื่อภัยคุกคามทาง physiology", "การรอ classification ไม่ตอบการดูแลเร่งด่วน"] }
  },
  { id: "M2N1", key: 0, retryKey: 1, visuals: [{ assetId: "A15", placement: "feedback", role: "teaching_example" }],
    en: { phase: "Imaging context", stem: "A 40-year-old pedestrian is currently stable after assessment, with persistent posterior pelvic pain. A binder is documented as already in place on arrival and remains in place during this review. The case uses a textual AP report.", question: "What would you check before reviewing the report?", choices: ["Image quality, orientation and the documented binder status.", "The final fracture subtype before checking the image context.", "The normal current BP as confirmation of a reassuring image."], reasons: ["Image context and a binder's potential effect help establish interpretation limits.", "Classification follows an ordered review of available evidence.", "Current circulation does not determine the image findings or mechanical stability."], facts: ["Stable after assessment; still monitored", "Posterior pelvic pain", "Binder documented at arrival; remains in place"], retry: "The AP report has arrived, but image context has not been recorded. What would you clarify?", retryChoices: ["Whether current BP proves that posterior structures are intact.", "Whether image quality, orientation and binder status are documented.", "Whether a fracture subtype can replace further image review."], retryReasons: ["BP cannot establish structural integrity.", "These details help interpret the report's limitations.", "A label does not replace an evidence review."] },
    th: { phase: "บริบทภาพ", stem: "ผู้ป่วยอายุ 40 ปีถูกรถชน ขณะนี้ stable หลังประเมิน แต่ยังปวด posterior pelvis เมื่อมาถึงบันทึกว่ามี binder อยู่แล้วและยังคงไว้ระหว่างการทบทวนนี้ เคสใช้รายงาน AP แบบข้อความ", question: "ก่อนอ่านรายงาน คุณจะตรวจสอบอะไร?", choices: ["คุณภาพภาพ orientation และ binder status ที่บันทึกไว้", "Final fracture subtype ก่อนตรวจบริบทของภาพ", "ใช้ BP ปกติยืนยันว่าภาพไม่น่ากังวล"], reasons: ["บริบทภาพและผลของ binder ช่วยกำหนดข้อจำกัดการแปลผล", "Classification ตามหลังการทบทวนหลักฐานอย่างเป็นระบบ", "Circulation ตอนนี้ไม่กำหนด imaging findings หรือ mechanical stability"], facts: ["Stable หลังประเมินและยัง monitored", "Posterior pelvic pain", "บันทึก binder เมื่อมาถึงและยังคงไว้"], retry: "ได้รายงาน AP แล้วแต่ยังไม่มีบริบทภาพ คุณจะถามเพิ่มอะไร?", retryChoices: ["BP ตอนนี้ยืนยันว่า posterior structures ปกติหรือไม่", "มีข้อมูลคุณภาพ orientation และ binder status หรือไม่", "ใช้ fracture subtype แทนการทบทวนภาพต่อได้หรือไม่"], retryReasons: ["BP ไม่ยืนยัน structural integrity", "ข้อมูลเหล่านี้ช่วยแปลข้อจำกัดของรายงาน", "Label ไม่แทนการทบทวนหลักฐาน"] }
  },
  { id: "M2N2", key: 1, retryKey: 2, visuals: [{ assetId: "A14", placement: "question", role: "teaching_example" }, { assetId: "A15", placement: "feedback", role: "teaching_example" }],
    en: { phase: "Ring evidence", stem: "The fictional AP report describes pubic rami fractures and asymmetry around the sacroiliac region. Posterior pain persists. Your senior asks which findings should be reviewed together.", question: "How would you organize the next review?", choices: ["Focus on the rami fractures before returning to the posterior concern.", "Review anterior injury and the posterior-region concern together.", "Use the anterior finding to classify stability without further review."], reasons: ["This risks delaying clarification of the already described posterior concern.", "The pelvic ring should be considered as a whole using the stated anterior and posterior evidence.", "Anterior evidence alone does not establish the ring's stability."], facts: ["Rami fractures described", "Sacroiliac-region asymmetry described"], retry: "The team has identified anterior injury. Which unresolved finding should remain in the assessment?", retryChoices: ["The anterior fractures alone establish the complete ring pattern.", "Current normal circulation removes the posterior pain concern.", "The sacroiliac-region finding and posterior pain need clarification."], retryReasons: ["The posterior ring cannot be assumed from anterior findings.", "Physiological stability does not remove structural concerns.", "The stated posterior evidence belongs in the continuing ring review."] },
    th: { phase: "หลักฐานของ ring", stem: "รายงาน AP สมมติระบุ pubic rami fractures และความไม่สมมาตรบริเวณ sacroiliac ยังปวดด้านหลัง อาจารย์ถามว่าควรทบทวน findings ใดร่วมกัน", question: "คุณจะจัดการทบทวนต่ออย่างไร?", choices: ["เน้น rami fractures ก่อนกลับมาดู posterior concern", "ทบทวน anterior injury และ posterior concern ร่วมกัน", "ใช้ anterior finding จำแนก stability โดยไม่ทบทวนเพิ่ม"], reasons: ["เสี่ยงทำให้การชี้แจง posterior concern ที่มีแล้วล่าช้า", "พิจารณา pelvic ring ทั้งวงจาก anterior และ posterior evidence ที่ระบุ", "Anterior evidence อย่างเดียวไม่ยืนยัน ring stability"], facts: ["รายงาน rami fractures", "รายงาน sacroiliac-region asymmetry"], retry: "ทีมพบ anterior injury แล้ว finding ใดที่ยังต้องอยู่ในการประเมิน?", retryChoices: ["Anterior fractures อย่างเดียวกำหนด ring pattern ครบแล้ว", "Circulation ปกติทำให้ไม่ต้องกังวล posterior pain", "Sacroiliac-region finding และ posterior pain ยังต้องชี้แจง"], retryReasons: ["ไม่ควรอนุมาน posterior ring จาก anterior findings", "Physiological stability ไม่ลบ structural concerns", "Posterior evidence ที่ระบุต้องอยู่ในการทบทวน ring ต่อ"] }
  },
  { id: "M2N3", key: 2, retryKey: 0, visuals: [{ assetId: "V2_LIGAMENTS", placement: "feedback", role: "teaching_example" }],
    en: { phase: "Stability judgments", stem: "The current BP is 122/76 mmHg while monitoring continues. The posterior-region concern has not yet been clarified. A colleague asks whether the normal BP proves that the ring is stable.", question: "How would you respond?", choices: ["Normal BP supports treating the ring as mechanically stable.", "Posterior pain establishes mechanical instability without imaging.", "Current circulation and mechanical stability require separate judgments."], reasons: ["Normal BP does not establish structural stability.", "Pain warrants assessment but does not establish the exact structural pattern.", "Current physiological stability can coexist with unresolved mechanical stability."], facts: ["BP 122/76 mmHg", "Mechanical stability remains unresolved"], retry: "The patient remains physiologically stable. Which question still needs structural evidence?", retryChoices: ["Whether the pelvic ring is mechanically stable.", "Whether one normal BP value completes all trauma assessment.", "Whether pain alone identifies a specific ligament disruption."], retryReasons: ["Mechanical stability depends on the ring injury and supporting structures.", "A single BP value does not complete assessment.", "Pain does not identify a specific ligament injury."] },
    th: { phase: "แยก stability", stem: "BP ตอนนี้ 122/76 mmHg และยัง monitoring ส่วน posterior concern ยังไม่ชัด เพื่อนถามว่า BP ปกติยืนยันว่า ring stable หรือไม่", question: "คุณจะตอบอย่างไร?", choices: ["BP ปกติสนับสนุนให้ถือว่า ring mechanically stable", "Posterior pain ยืนยัน mechanical instability โดยไม่ต้อง imaging", "Circulation ปัจจุบันและ mechanical stability ต้องประเมินแยกกัน"], reasons: ["BP ปกติไม่ยืนยัน structural stability", "อาการปวดต้องประเมิน แต่ไม่ระบุ structural pattern ที่แน่ชัด", "Physiological stability อาจอยู่ร่วมกับ mechanical stability ที่ยังไม่ทราบ"], facts: ["BP 122/76 mmHg", "Mechanical stability ยังไม่ชัด"], retry: "ผู้ป่วยยัง physiologically stable คำถามใดยังต้องใช้ structural evidence?", retryChoices: ["Pelvic ring mechanically stable หรือไม่", "BP ปกติครั้งเดียวทำให้ trauma assessment ครบหรือไม่", "อาการปวดอย่างเดียวระบุ ligament disruption ได้หรือไม่"], retryReasons: ["Mechanical stability ขึ้นกับ ring injury และ supporting structures", "BP ครั้งเดียวไม่ทำให้ assessment ครบ", "อาการปวดไม่ระบุ ligament injury เฉพาะ"] }
  },
  { id: "M2N4", key: 1, retryKey: 2,
    en: { phase: "Imaging and binder plan", stem: "The patient has sustained monitored stability. Posterior pain and concerning AP findings persist; the binder remains in place. Appropriate CT and specialist review are available safely.", question: "Which next plan would you discuss with the senior?", choices: ["Remove the binder now and arrange imaging after a routine review.", "Obtain appropriate imaging and agree a monitored reassessment/removal plan.", "Keep the binder without further imaging until posterior pain settles."], reasons: ["Binder removal needs a coordinated senior plan; a bound image can mask displacement.", "Use safe imaging access and senior review while monitoring continues; agree how and when to reassess the binder.", "Persistent posterior concern requires clarification; retaining a binder does not replace review."], facts: ["Sustained monitored stability", "CT and specialist review available safely", "Binder remains in place"], retry: "The team asks whether a reassuring bound image would be enough to remove the binder immediately.", retryChoices: ["Use a reassuring bound image as the only removal criterion.", "Keep the binder indefinitely because imaging cannot help.", "Agree senior reassessment, imaging and a monitored removal plan."], retryReasons: ["A binder may reduce and mask disruption; image appearance alone is insufficient here.", "A binder is temporary and requires a reassessment plan.", "The team must interpret bound images in context and coordinate removal."] },
    th: { phase: "แผน imaging และ binder", stem: "ผู้ป่วยมี sustained monitored stability แต่ posterior pain และ AP findings ยังน่ากังวล Binder ยังอยู่ สามารถทำ CT และ specialist review ได้อย่างปลอดภัย", question: "คุณจะหารือแผนต่อใดกับอาจารย์?", choices: ["ถอด binder ตอนนี้และรอ imaging หลัง routine review", "ทำ imaging ที่เหมาะสมและตกลงแผน monitored reassessment/removal", "คง binder โดยไม่ imaging เพิ่มจน posterior pain หาย"], reasons: ["การถอดต้องมี senior plan และภาพขณะมี binder อาจ mask displacement", "ใช้ safe imaging access และ senior review ระหว่าง monitoring พร้อมตกลงวิธีและเวลาทบทวน binder", "Posterior concern ที่ยังอยู่ต้องชี้แจง การคง binder ไม่แทน review"], facts: ["Sustained monitored stability", "CT และ specialist review เข้าถึงได้ปลอดภัย", "ยังมี binder"], retry: "ทีมถามว่าภาพขณะมี binder ที่ดู reassuring เพียงพอให้ถอดทันทีหรือไม่", retryChoices: ["ใช้ภาพที่ reassuring เป็นเกณฑ์ถอดเพียงข้อเดียว", "คง binder ไม่มีกำหนดเพราะ imaging ช่วยไม่ได้", "ตกลง senior reassessment, imaging และ monitored removal plan"], retryReasons: ["Binder อาจ reduce และ mask disruption จึงใช้ภาพอย่างเดียวไม่ได้ในบริบทนี้", "Binder เป็นอุปกรณ์ชั่วคราวที่ต้องมี reassessment plan", "ทีมต้องอ่านภาพตามบริบทและประสานการถอด"] }
  },
  { id: "M2N5", key: 2, retryKey: 1,
    en: { phase: "Imaging handover", stem: "Your senior asks for a concise update. Anterior injury is described, posterior involvement and mechanical stability remain uncertain, and current circulation is stable while monitored.", question: "Which update best represents the evidence?", choices: ["Current BP is normal; the anterior injury establishes a stable ring.", "Posterior pain persists; this establishes the definitive treatment.", "Anterior injury is described; posterior involvement needs clarification."], reasons: ["This incorrectly uses physiology and anterior injury to establish mechanical stability.", "Pain and the available report do not establish definitive treatment.", "State what is known, the unresolved posterior concern, monitoring and the agreed review plan."], facts: ["Anterior injury described", "Posterior involvement and stability uncertain", "Current circulation stable while monitored"], retry: "The receiving clinician asks what is known and what remains uncertain.", retryChoices: ["Normal BP establishes both circulation and ring stability.", "Anterior injury is known; posterior concern still needs review.", "Posterior pain alone establishes the fracture subtype."], retryReasons: ["These are separate judgments.", "This states the evidence and the remaining uncertainty.", "Pain does not establish a subtype."] },
    th: { phase: "Handover เรื่อง imaging", stem: "อาจารย์ขอสรุปสั้น ๆ มี anterior injury ตามรายงาน แต่ posterior involvement และ mechanical stability ยังไม่ชัด Circulation ขณะนี้ stable และ monitored", question: "ข้อความใดสะท้อนหลักฐานได้เหมาะสม?", choices: ["BP ปกติ และ anterior injury ยืนยัน stable ring", "ยังปวดด้านหลัง จึงกำหนด definitive treatment ได้แล้ว", "รายงาน anterior injury แต่ posterior involvement ยังต้องชี้แจง"], reasons: ["ใช้ physiology และ anterior injury ยืนยัน mechanical stability อย่างไม่เหมาะสม", "อาการปวดและรายงานที่มีไม่กำหนด definitive treatment", "บอกสิ่งที่ทราบ posterior concern ที่ยังไม่ชัด monitoring และแผน review ที่ตกลง"], facts: ["มี anterior injury ตามรายงาน", "Posterior involvement และ stability ยังไม่ทราบ", "Circulation stable ขณะ monitoring"], retry: "ทีมรับต่อถามว่าสิ่งใดทราบแล้วและสิ่งใดยังไม่แน่ชัด", retryChoices: ["BP ปกติยืนยันทั้ง circulation และ ring stability", "ทราบ anterior injury ส่วน posterior concern ยังต้อง review", "Posterior pain อย่างเดียวกำหนด fracture subtype"], retryReasons: ["เป็นคนละการประเมิน", "บอกหลักฐานและ uncertainty ได้ตรง", "อาการปวดไม่กำหนด subtype"] }
  },
  { id: "M3N1", key: 0, retryKey: 2, visuals: [{ assetId: "V2_ASSOCIATED", placement: "feedback", role: "teaching_example" }],
    en: { phase: "Wound concern", stem: "A 32-year-old man after a crush injury has a pelvic ring injury. Circulation has improved and remains monitored. During the continuing assessment, the team identifies a small perineal wound without visible bone.", question: "What concern would you raise with your senior?", choices: ["Possible open pelvic injury needs urgent appropriate assessment.", "The wound is small, so review can wait for the fracture classification.", "No bone is visible, so the injury can be documented as closed."], reasons: ["A wound may communicate with the injury without visible bone; raise concern without claiming proof.", "Wound size does not determine the urgency of possible communication.", "Absent visible bone does not exclude an open injury."], facts: ["Pelvic ring injury after crush mechanism", "Small perineal wound; no visible bone", "Circulation improved, still monitored"], retry: "Your colleague asks whether the absence of visible bone excludes an open injury in this patient.", retryChoices: ["Yes; visible bone is required to raise an open-injury concern.", "Wound size alone determines whether communication is possible.", "No; possible communication still needs urgent assessment."], retryReasons: ["An open injury does not require visible bone.", "Size alone does not determine communication.", "Escalate the concern for appropriate assessment."] },
    th: { phase: "พบแผลที่ต้องกังวล", stem: "ชายอายุ 32 ปีหลัง crush injury มี pelvic ring injury Circulation ดีขึ้นและยัง monitored ระหว่างประเมินต่อ ทีมพบแผล perineum เล็กโดยไม่เห็นกระดูก", question: "คุณจะรายงานข้อกังวลใดให้อาจารย์?", choices: ["สงสัย open pelvic injury ต้องประเมินอย่างเหมาะสมเร่งด่วน", "แผลเล็กจึงรอ review หลังจำแนก fracture ได้", "ไม่เห็นกระดูกจึงบันทึกว่าเป็น closed injury ได้"], reasons: ["แผลอาจ communicate กับ injury แม้ไม่เห็นกระดูก จึงรายงานความสงสัยโดยไม่ยืนยันเกินหลักฐาน", "ขนาดแผลไม่กำหนดความเร่งด่วนของ possible communication", "การไม่เห็นกระดูกไม่ตัด open injury"], facts: ["Pelvic ring injury หลัง crush mechanism", "แผล perineum เล็ก ไม่เห็นกระดูก", "Circulation ดีขึ้นและยัง monitored"], retry: "เพื่อนถามว่าการไม่เห็นกระดูกตัด open injury ในรายนี้ได้หรือไม่", retryChoices: ["ได้ เพราะต้องเห็นกระดูกจึงสงสัย open injury", "ขนาดแผลอย่างเดียวกำหนด possible communication", "ไม่ได้ ยังต้องประเมิน possible communication เร่งด่วน"], retryReasons: ["Open injury ไม่จำเป็นต้องเห็นกระดูก", "ขนาดอย่างเดียวไม่กำหนด communication", "Escalate ข้อกังวลเพื่อประเมินอย่างเหมาะสม"] }
  },
  { id: "M3N2", key: 2, retryKey: 0, visuals: [{ assetId: "V2_ASSOCIATED", placement: "feedback", role: "teaching_example" }],
    en: { phase: "Urinary warning", stem: "The ongoing assessment also identifies blood at the urethral meatus. Urinary output assessment is being discussed; no specific urethral injury has been established.", question: "What would you communicate before catheter attempts?", choices: ["Try repeated blind attempts before requesting further assessment.", "Meatal blood confirms complete transection and determines drainage.", "Raise suspected urethral injury and seek the senior evaluation plan."], reasons: ["Repeated blind attempts risk further harm; this is not a supervised student's task.", "The sign raises suspicion but does not establish the type of injury or the drainage choice.", "Communicate the warning and avoid blind student/repeated attempts; the experienced team follows the local evaluation/drainage pathway."], facts: ["Blood at urethral meatus", "Exact urethral injury unconfirmed"], retry: "The team asks what meatal bleeding establishes in this patient.", retryChoices: ["Suspicion of urethral injury requiring appropriate team evaluation.", "Proof of complete transection requiring one universal drainage method.", "Permission to continue repeated blind attempts before senior review."], retryReasons: ["The warning warrants escalation without overstating the diagnosis.", "A single sign cannot establish injury extent or one drainage method.", "Repeated blind attempts risk harm; the experienced team decides the pathway."] },
    th: { phase: "Urinary warning", stem: "ระหว่างประเมินพบเลือดที่ urethral meatus ทีมกำลังหารือการประเมิน urinary output แต่ยังไม่ยืนยัน urethral injury ชนิดใด", question: "ก่อนใส่สายสวน คุณจะสื่อสารอย่างไร?", choices: ["ลอง blind attempts ซ้ำก่อนขอประเมินเพิ่ม", "Meatal blood ยืนยัน complete transection และกำหนด drainage", "รายงาน suspected urethral injury และขอ senior evaluation plan"], reasons: ["Blind attempts ซ้ำเสี่ยงเพิ่มอันตรายและไม่ใช่หน้าที่นักศึกษา", "Sign นี้เพิ่มความสงสัยแต่ไม่ระบุชนิด injury หรือวิธี drainage", "สื่อสาร warning และหลีกเลี่ยง blind attempts ของนักศึกษาหรือการทำซ้ำ ให้ทีมมีประสบการณ์ใช้ local pathway"], facts: ["มีเลือดที่ urethral meatus", "ยังไม่ยืนยันชนิด urethral injury"], retry: "ทีมถามว่า meatal bleeding บอกอะไรในรายนี้", retryChoices: ["สงสัย urethral injury ที่ต้องให้ทีมประเมินอย่างเหมาะสม", "ยืนยัน complete transection ที่ใช้ drainage วิธีเดียวทุกราย", "ทำ blind attempts ซ้ำได้ก่อน senior review"], retryReasons: ["Warning ต้อง escalation โดยไม่กล่าว diagnosis เกินหลักฐาน", "Sign เดียวไม่ระบุ extent หรือ drainage วิธีเดียว", "การทำซ้ำเสี่ยงอันตราย ทีมมีประสบการณ์เป็นผู้ตัดสิน pathway"] }
  },
  { id: "M3N3", key: 1, retryKey: 2, visuals: [{ assetId: "V2_ASSOCIATED", placement: "question", role: "teaching_example" }],
    en: { phase: "Coordinated assessment", stem: "Trauma care continues. The perineal wound and urinary warning both need senior coordination while circulation remains monitored. You are asked which concerns belong in the joint review.", question: "Which plan would you bring to the team?", choices: ["Focus on orthopaedic classification before discussing the wound and urine.", "Coordinate ongoing trauma care with urgent wound and urinary assessment.", "Focus on urinary drainage before returning to the trauma and wound review."], reasons: ["This delays associated-injury concerns that are already present.", "Keep trauma priorities active while the senior team coordinates appropriate specialists and the local open-injury pathway.", "Urinary assessment must be coordinated with the wider trauma and wound concerns."], facts: ["Possible open injury", "Suspected urethral injury", "Supervised learner role"], retry: "The draft plan covers the ring injury but leaves out the wound and meatal bleeding. What would you add?", retryChoices: ["A definitive operation based on the mechanism alone.", "A routine follow-up after the fracture classification is complete.", "Urgent associated-injury review alongside ongoing trauma care."], retryReasons: ["Definitive treatment cannot be established from the mechanism alone.", "This postpones urgent associated concerns.", "The wound and urinary warning belong in a coordinated senior assessment."] },
    th: { phase: "ประสานการประเมิน", stem: "ทีมยังทำ trauma care แผล perineum และ urinary warning ต้องประสานกับทีมอาวุโสขณะ monitoring circulation คุณได้รับหน้าที่เสนอข้อกังวลในการ review ร่วม", question: "คุณจะเสนอแผนใดต่อทีม?", choices: ["เน้น orthopaedic classification ก่อนหารือแผลและปัสสาวะ", "ประสาน trauma care ต่อกับ wound และ urinary assessment เร่งด่วน", "เน้น urinary drainage ก่อนกลับมาทบทวน trauma และแผล"], reasons: ["ทำให้ associated-injury concerns ที่มีแล้วล่าช้า", "คง trauma priorities พร้อมให้ทีมอาวุโสประสาน specialists และ local open-injury pathway", "ต้องประสาน urinary assessment กับ trauma และ wound concerns ด้วย"], facts: ["Possible open injury", "Suspected urethral injury", "ผู้เรียนอยู่ภายใต้การกำกับ"], retry: "แผนระบุ ring injury แต่ไม่กล่าวแผลและ meatal bleeding คุณจะเติมอะไร?", retryChoices: ["Definitive operation จาก mechanism อย่างเดียว", "Routine follow-up เมื่อจำแนก fracture เสร็จ", "Urgent associated-injury review พร้อม trauma care ต่อ"], retryReasons: ["Mechanism อย่างเดียวไม่กำหนด definitive treatment", "ทำให้ข้อกังวลเร่งด่วนล่าช้า", "แผลและ urinary warning ต้องอยู่ใน senior assessment ที่ประสานกัน"] }
  },
  { id: "M3N4", key: 0, retryKey: 1,
    en: { phase: "Associated-injury handover", stem: "Prepare the referral while monitoring and trauma care continue. The wound raises possible open injury; meatal bleeding raises suspected urethral injury. Neither has been definitively characterized.", question: "Which opening states the concern accurately?", choices: ["Possible open pelvic and urethral injuries; urgent joint review requested.", "Confirmed complete urethral transection; definitive repair requested.", "Improved circulation; routine review of the wound and urine requested."], reasons: ["Communicate suspicion, current physiology, actions and an explicit urgent request without inventing certainty.", "The signs do not establish complete transection or definitive treatment.", "Improved circulation does not remove the separate urgent wound and urinary concerns."], facts: ["Possible open pelvic injury", "Suspected urethral injury", "Circulation improved, still monitored"], retry: "The draft referral calls the urethral injury confirmed. How would you correct it?", retryChoices: ["Call it confirmed because meatal blood establishes the full extent.", "State suspected injury and request urgent assessment with current status.", "Remove the urinary concern because the circulation has improved."], retryReasons: ["The sign does not establish the full injury.", "Use evidence-based uncertainty and a clear urgent request.", "Improved circulation does not erase the urinary warning."] },
    th: { phase: "Handover associated injuries", stem: "เตรียม referral ระหว่าง monitoring และ trauma care แผลทำให้สงสัย open injury ส่วน meatal bleeding ทำให้สงสัย urethral injury โดยยังไม่ระบุลักษณะที่แน่ชัด", question: "คำเปิดใดระบุข้อกังวลได้ตรงหลักฐาน?", choices: ["สงสัย open pelvic และ urethral injuries ขอ urgent joint review", "ยืนยัน complete urethral transection ขอ definitive repair", "Circulation ดีขึ้น ขอ routine wound และ urinary review"], reasons: ["สื่อสาร suspicion, physiology, actions และคำขอเร่งด่วนโดยไม่สร้างความแน่นอน", "Signs ไม่ยืนยัน complete transection หรือ definitive treatment", "Circulation ดีขึ้นไม่ลบข้อกังวลเร่งด่วนของแผลและ urinary injury"], facts: ["Possible open pelvic injury", "Suspected urethral injury", "Circulation ดีขึ้นและยัง monitored"], retry: "Referral ระบุว่า urethral injury ยืนยันแล้ว คุณจะแก้อย่างไร?", retryChoices: ["ยืนยันต่อเพราะ meatal blood ระบุ extent ครบแล้ว", "ระบุ suspected injury และขอ urgent assessment พร้อม current status", "ตัด urinary concern เพราะ circulation ดีขึ้น"], retryReasons: ["Sign ไม่ยืนยัน injury ทั้งหมด", "ใช้ uncertainty ตามหลักฐานและคำขอเร่งด่วนชัดเจน", "Circulation ดีขึ้นไม่ลบ urinary warning"] }
  }
];

const makeOptions = (id: string, copy: Copy, key: number, retry = false): Option[] => (retry ? copy.retryChoices : copy.choices).map((text, index) => ({ id: `${id}_${"ABC"[index]}`, text, explanation: `${index === key ? "Preferred" : "Why not"}: ${(retry ? copy.retryReasons : copy.reasons)[index]}` }));
const handovers = new Set(["M1N6", "M2N5", "M3N4"]);
const nodes: Node[] = revisions.map((revision) => {
  const previous = legacy.nodes.find((node) => node.id === revision.id)!;
  const missionNodes = revisions.filter((item) => item.id.startsWith(revision.id.slice(0, 2)));
  const next = missionNodes[missionNodes.indexOf(revision) + 1]?.id ?? null;
  return { ...previous, contentVersion: REVISION_ID, stem: revision.en.stem, question: revision.en.question, factsAvailableNow: revision.en.facts, options: makeOptions(revision.id, revision.en, revision.key), correctOptionIds: [`${revision.id}_${"ABC"[revision.key]}`], nextNodeId: next, scenePhase: revision.en.phase, rationaleRequired: handovers.has(revision.id), rationalePrompt: handovers.has(revision.id) ? "Add one short handover reason or uncertainty." : "Optional note", interaction: handovers.has(revision.id) ? "handover" : revision.id === "M1N3" ? "image_choice" : "action", assetId: null, visuals: revision.visuals ?? [], textAlternative: "Use the stated case evidence. Teaching examples are not images of this fictional patient." };
});

const teachingAsset = (id: string, path: string, sourceUrl: string, caption: string, altText: string): Asset => ({ id, path, sourceUrl, caption, altText, versionHash: REVISION_ID, owner: "Supplied teaching resource", licensePermission: "User supplied for course use; publication reuse review pending", reviewStatus: "pending", reviewer: null, reviewDate: null, optional: false, downloadBytes: 200000 });
export const revisedAssets: Asset[] = [
  teachingAsset("V2_BINDER", "/assets/teaching/binder-manikin-page17.jpg", "/resources/pelvic-fracture-teaching-handout-th.pdf#page=17", "Binder landmark on a training manikin — supplied handout, page 17, Figure 12", "Three training-manikin photographs showing binder placement at the greater-trochanter level; this is a teaching example, not the case patient"),
  teachingAsset("V2_LIGAMENTS", "/assets/teaching/slide-5.jpg", "/resources/pelvic-fracture-medical-student-2024.pdf#page=5", "Pelvic ligaments and stability — supplied slides, page 5", "Anterior and posterior pelvic structures with labelled supporting ligaments; teaching anatomy, not patient imaging"),
  teachingAsset("V2_ASSOCIATED", "/assets/teaching/slide-11.jpg", "/resources/pelvic-fracture-medical-student-2024.pdf#page=11", "Associated-injury anatomy — supplied slides, page 11", "Anatomical illustration of pelvic vessels, nerves and nearby gastrointestinal and genitourinary structures; no patient photograph"),
  ...[1, 2, 3].map((number) => ({ ...teachingAsset(`V2_PATIENT_${number}`, `/assets/patients-v2/patient-${number}.png`, "", `Fictional patient ${number} on a supported emergency stretcher`, `Fictional adult ${number === 3 ? "man " : "patient "}lying supported on a stretcher, dressed and covered; decorative game artwork`), owner:"Generated fictional game artwork", licensePermission:"Generated decorative asset; educator visual review pending; not a diagnostic illustration", downloadBytes:[1500311,1484634,1926700][number-1] }))
];
const missions = legacy.missions.map((mission) => ({ ...mission, contentVersion: REVISION_ID, nodeIds: nodes.filter((node) => node.missionId === mission.id).map((node) => node.id), entry: nodes.find((node) => node.missionId === mission.id)!.stem }));
export const pelvicTraumaContentV2: ContentVersion = {
  ...legacy, id: REVISION_ID,
  governance: { author: "Course content team", reviewer: null, reviewDate: null, status: "draft", supersedesVersion: legacy.id },
  missions, nodes,
  corrections: revisions.map((revision) => {
    const previous = legacy.corrections.find((item) => item.parentNodeId === revision.id)!;
    return { ...previous, contentVersion: REVISION_ID, stem: revision.en.retry, options: makeOptions(previous.id, revision.en, revision.retryKey, true), correctOptionId: `${previous.id}_${"ABC"[revision.retryKey]}`, workedExample: `${revision.en.retryChoices[revision.retryKey]} ${revision.en.retryReasons[revision.retryKey]}` };
  }),
  assets: [...legacy.assets.map((asset) => asset.id === "A16" ? { ...asset, altText: "Three supplied drawings of pelvic stabilization devices; not a validated comparison of correct and incorrect landmark positions", caption: "Pelvic stabilization illustrations — supplied slides, page 34" } : asset), ...revisedAssets],
  resources: legacy.resources.map((resource) => ({ ...resource, contentVersion: REVISION_ID, assetIds: resource.id === "R1" ? ["A14", "A15", "V2_LIGAMENTS"] : resource.id === "R2" ? ["V2_ASSOCIATED"] : resource.id === "R3" ? ["V2_BINDER"] : resource.assetIds,
    body: resource.id === "ORIENTATION" ? ["Walk to a patient, review the team update and choose an action. Your patient chart and reference cards remain available. Notes and confidence are optional except for a brief reason or uncertainty at each case handover.", "Review feedback and correct missed decisions in the same step. Collect safety badges, case stamps and reward toward five clothing levels. Finishing through corrections can unlock the best outfit.", "Complete the three patient stories, review your handovers and finish the shift. The game supports supervised reasoning and does not certify independent trauma or procedural competence."] : resource.body }))
};
contentVersionSchema.parse(pelvicTraumaContentV2);
const errors = validateContentLinks(pelvicTraumaContentV2);
if (errors.length) throw new Error(errors.join("; "));

export const revisedMissionThai: Record<string, { title: string; entry: string }> = {
  "mission-1": { title: "ผู้ป่วยที่ระบบไหลเวียนไม่คงที่", entry: revisions[0].th.stem },
  "mission-2": { title: "ผู้ป่วยที่ circulation stable แต่ ring ยังไม่ชัด", entry: revisions[6].th.stem },
  "mission-3": { title: "แผลและ associated injuries ที่ต้องระวัง", entry: revisions[11].th.stem }
};
export const revisionById = new Map(revisions.map((revision) => [revision.id, revision]));
