// Authenticated QA checks use only a fictional learner. Never print session credentials.
const url=process.env.VITE_SUPABASE_URL,key=process.env.VITE_SUPABASE_PUBLISHABLE_KEY,courseId=process.env.VITE_COURSE_ID;
if(!url||!key||!courseId)throw new Error("Connected public configuration required");
async function call(name:string,body:unknown,token?:string){return fetch(`${url}/functions/v1/${name}`,{method:"POST",headers:{"Content-Type":"application/json",apikey:key!,...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});}
const entry=await call("learner-entry",{courseId,email:"qa.pelvic.20261008@example.invalid",studentId:"QA-ENTRY-1008"});
if(!entry.ok)throw new Error(`QA entry failed: ${entry.status}`);
const data=await entry.json(),token=data.session?.access_token;if(!token)throw new Error("No authenticated QA session");
for(const name of ["faculty-workspace","sheets-status"]){const response=await call(name,{courseId,operation:"summary"},token);if(response.status!==403)throw new Error(`${name} did not deny learner access`);console.log(`${name}: learner denied (403)`);}
const context=await call("learner-context",{courseId},token),profile=await context.json();if(!context.ok||profile.profile?.studentId!=="QA-ENTRY-1008")throw new Error("Profile mismatch");console.log("Own learner profile: verified");
const attempts=await call("learner-attempts",{courseId},token),saved=await attempts.json();if(!attempts.ok||!saved.attempts.some((a:{attemptId:string;events:unknown[]})=>a.attemptId==="c5015f83-5694-4c9c-bbfe-6e2782311b36"&&a.events.length===2))throw new Error("Accepted evidence not resumed");console.log("Accepted original evidence: 2 immutable events verified");
const conflict=await call("learner-entry",{courseId,email:"qa.pelvic.20261008@example.invalid",studentId:"DIFFERENT-ID"});if(conflict.status!==409)throw new Error("Identity conflict not rejected");const rejected=await conflict.json();if(rejected.session)throw new Error("Conflict issued a session");console.log("Conflicting email/ID: denied (409), no session issued");
const unauthenticated=await call("learner-attempts",{courseId});if(unauthenticated.status!==401)throw new Error("Unauthenticated evidence allowed");console.log("Unauthenticated evidence access: denied (401)");
for(const name of ["learner-context","learner-attempts","start-attempt","sync-events","completion-status","cohort-leaderboard","faculty-workspace","sheets-status"]){const response=await call(name,null,token);if(response.status!==400)throw new Error(`${name}: malformed request returned ${response.status}`);}console.log("Malformed requests: all 8 authenticated interfaces reject safely (400)");
const other=await call("completion-status",{courseId,attemptId:"7a529380-d6d2-44bc-bf3b-2efc30dfef65"},token);if(other.status!==403)throw new Error("Other learner receipt accessible");console.log("Other account completion receipt: denied (403)");
const worker=await call("sheets-worker",{operation:"verify"},token);if(worker.status!==401)throw new Error("Learner accessed export worker");console.log("Privileged Sheets worker: learner denied (401)");
const original=saved.attempts.find((a:{attemptId:string})=>a.attemptId==="c5015f83-5694-4c9c-bbfe-6e2782311b36");
const replayEvents=original.events.map((event:Record<string,unknown>)=>{const {serverReceiptTimestamp,...payload}=event;return payload;});
const replay=await call("sync-events",{courseId,events:replayEvents},token),result=await replay.json();if(!replay.ok||result.acknowledgments?.length!==2||result.rejected?.length||result.retryable?.length)throw new Error(`Immutable replay failed: status ${replay.status}; ${JSON.stringify({rejected:result.rejected,retryable:result.retryable,error:result.error})}`);console.log("Existing event replay: both acknowledged, no conflicting or retryable records");
const altered=await call("sync-events",{courseId,events:[{...replayEvents[0],clientTimestamp:"2026-10-01T00:00:00.000Z"}]},token),alteredResult=await altered.json();if(!altered.ok||alteredResult.acknowledgments?.length||alteredResult.rejected?.[0]?.reason!=="Event ID was reused with altered data")throw new Error("Altered immutable evidence accepted");console.log("Altered immutable event: rejected, original evidence preserved");
