import {describe,expect,it} from "vitest";
import {buildSheetRows,demoExamples,safeSheetCell,type SheetLearner,type SheetAttempt} from "./sheets";
import {focusedJourney} from "../content/focused.test";
import {pelvicTraumaContentV5 as latestContent} from "../content/content.v5";
const learner:SheetLearner={userId:"learner",studentId:"001234",email:"student@example.edu",identityStatus:"self_reported",cohortId:"cohort",registeredAt:"2026-10-07T18:00:00Z"};
const attempt=(wrong=false):SheetAttempt=>({userId:"learner",learnerId:"001234",attemptId:"focused",cohortId:"cohort",contentVersion:latestContent.id,reportingStatus:"reporting",kind:"initial",createdAt:"2026-10-07T18:00:00Z",completedAt:"2026-10-08T00:00:01Z",events:focusedJourney(wrong)});
describe("Google Sheets assessment records",()=>{
 it("computes six fictional examples through the engine and excludes them from real records",()=>{const demo=demoExamples();expect(demo).toHaveLength(7);expect(demo.find(row=>row[3]==="all_first_correct")?.[9]).toBe(250);expect(demo.find(row=>row[3]==="all_corrected")?.[9]).toBe(220);expect(demo.slice(1).every(row=>row[1]==="DEMO")).toBe(true);expect(buildSheetRows([],[],[],"https://game.example")["Learner Results"]).toHaveLength(1);});
 it("keeps leading zeros, Bangkok dates, first answers and corrected performance separate",()=>{const rows=buildSheetRows([learner],[attempt(true)],[],"https://game.example");const result=rows["Learner Results"][1];expect(result[1]).toBe("001234");expect(result[7]).toBe("2026-10-08");expect(result.slice(12,18)).toEqual([0,15,15,0,0,220]);expect(rows["Decision Evidence"]).toHaveLength(16);expect(rows.Handovers).toHaveLength(4);expect(rows["Objective Analysis"].slice(1).every(row=>Number(row[8])===Number(row[10]))).toBe(true);});
 it("represents missing evidence separately and retains practice without replacing initial results",()=>{const notStarted=buildSheetRows([learner],[],[],"https://game.example")["Learner Results"][1];expect(notStarted[6]).toBe("not_started");expect(notStarted[16]).toBe(21);/* 3 pre-test + 15 cases + 3 post-test */const assessed=attempt(),practice={...attempt(true),attemptId:"practice",kind:"practice",reportingStatus:"practice",originalAttemptId:"focused"};const rows=buildSheetRows([learner],[assessed,practice],[],"https://game.example");expect(rows["Learner Results"].map(row=>row[0])).toEqual(["Record ID","ptd:attempt:focused","ptd:attempt:practice"]);expect(rows["Learner Results"][2][20]).toBe("focused");});
 it("protects authored content from formula injection",()=>{for(const text of ["=IMPORTXML()","+1","-1","@abc","\t=1"])expect(safeSheetCell(text)).toBe("'"+text);expect(safeSheetCell("001234")).toBe("001234");});
});
